/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;


import DTO.BordadoProducaoDTO;
import dao.BordadoProducaoDAO;
import CTR.tdgCTR;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PeDr0_HuG0
 */
public class BordadoProducaoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form ClienteVIEW
     */
    public BordadoProducaoVIEW() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        //botao x fechar apenas janela
        setDefaultCloseOperation(BordadoProducaoVIEW.HIDE_ON_CLOSE);
        
        //entar como tab
        tdgCTR.considerarEnterComoTab(jComboBox_turno);
        tdgCTR.considerarEnterComoTab(txt_maquina);
        tdgCTR.considerarEnterComoTab(txt_data);
        tdgCTR.considerarEnterComoTab(txt_ref);
        //tdgCTR.considerarEnterComoTab(jComboBox_cor);
        tdgCTR.considerarEnterComoTab(txt_pontos);
        tdgCTR.considerarEnterComoTab(txt_corte);
        tdgCTR.considerarEnterComoTab(txt_t1);
        tdgCTR.considerarEnterComoTab(txt_t2);
        tdgCTR.considerarEnterComoTab(txt_t3);
        tdgCTR.considerarEnterComoTab(txt_t4);
        tdgCTR.considerarEnterComoTab(txt_defeitos);
        tdgCTR.considerarEnterComoTab(txt_obs);
        
        
        jComboBox_turno.requestFocus();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_maquina = new javax.swing.JTextField();
        btn_Cadastrar = new javax.swing.JButton();
        txt_data = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_turno = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txt_ref = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_pontos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_corte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_t1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_t2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_t3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_t4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jComboBox_nome = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txt_obs = new javax.swing.JTextField();
        jComboBox_cor = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txt_defeitos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_Excluir = new javax.swing.JButton();
        btnListarTodos = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_data_pesquisar = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produção Bordado"));

        jLabel1.setText("DATA:");

        jLabel2.setText("NOME:");

        jLabel3.setText("MAQUINA");

        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });
        btn_Cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_CadastrarFocusGained(evt);
            }
        });

        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("TURNO:");

        jComboBox_turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MANHA", "TARDE", "NOITE" }));

        jLabel7.setText("REF:");

        jLabel8.setText("PONTOS:");

        jLabel9.setText("CORTE:");

        jLabel10.setText("COR:");

        jLabel11.setText("T1:");

        txt_t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_t1FocusLost(evt);
            }
        });

        jLabel12.setText("T2:");

        txt_t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_t2FocusLost(evt);
            }
        });

        jLabel13.setText("T3:");

        txt_t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_t3FocusLost(evt);
            }
        });

        jLabel14.setText("T4:");

        txt_t4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_t4FocusLost(evt);
            }
        });

        jLabel15.setText("TOTAL:");

        txt_total.setEditable(false);
        txt_total.setText("0");
        txt_total.setEnabled(false);

        jComboBox_nome.setEditable(true);
        jComboBox_nome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANDREA", "GEISE", "JANE", "JESSICA", "LIDIANE", "MARTA", "ROSIMARI", "TAIGRA", " " }));

        jLabel16.setText("OBS:");

        jComboBox_cor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AMARELO", "AREIA", "AZUL CELESTE", "AZUL COBALTO", "AZUL MEDIO", "BRANCO", "CHUMBO", "ESMERALDA", "LARANJA", "MARINHO", "MESCLA CLARO", "MESCLA ESCURO", "PINK", "PRETO", "ROSA", "ROXO", "RUBI", "VERDE CLARO", "VERDE LIMAO", "VERDE MUSGO", "VERDE PISCINA", "VERMELHO" }));

        jLabel17.setText("DEFEITOS:");

        txt_defeitos.setText("0");
        txt_defeitos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_defeitosFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maquina)
                            .addComponent(txt_data)
                            .addComponent(jComboBox_turno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pontos))
                            .addComponent(jComboBox_nome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_corte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_t1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_t2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_t3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_t4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_defeitos, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addComponent(txt_obs))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_pontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_corte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txt_defeitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(btn_Cadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_maquina.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_maquina.selectAll();
            }
        });
        txt_data.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_data.selectAll();
            }
        });
        txt_ref.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ref.selectAll();
            }
        });
        txt_pontos.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_pontos.selectAll();
            }
        });
        txt_corte.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_corte.selectAll();
            }
        });
        txt_t1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_t1.selectAll();
            }
        });
        txt_t2.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_t2.selectAll();
            }
        });
        txt_t3.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_t3.selectAll();
            }
        });
        txt_t4.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_t4.selectAll();
            }
        });
        txt_obs.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_obs.selectAll();
            }
        });
        txt_defeitos.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_defeitos.selectAll();
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar / Excluir"));

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btnListarTodos.setText("Listar Todos");
        btnListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodosActionPerformed(evt);
            }
        });

        btn_Limpar.setText("Limpar Tabela");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        jButton1.setText("RELATORIO BORDADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            txt_data_pesquisar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton2.setText("Pesquisar(fazer)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_data_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Excluir)
                    .addComponent(btnListarTodos)
                    .addComponent(btn_Limpar)
                    .addComponent(jButton1)
                    .addComponent(txt_data_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_data.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_data.selectAll();
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TURNO", "MAQUINA", "NOME", "DATA", "REF", "COR", "PONTOS", "CORTE", "T1", "T2", "T3", "T4", "TOTAL", "ERROS", "OBS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        //ocultar coluna ID da tabela
        jTable1.getColumnModel().getColumn( 0 ).setMaxWidth( 0 );
        jTable1.getColumnModel().getColumn( 0 ).setMinWidth( 0 );
        jTable1.getTableHeader().getColumnModel().getColumn( 0 ).setMaxWidth( 0 );
        jTable1.getTableHeader().getColumnModel().getColumn( 0 ).setMinWidth( 0 );
        //fim ocultar

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public void calc_total(){
        Integer T1;
        Integer T2;
        Integer T3;
        Integer T4;
        //T1
        if (txt_t1.getText().equals("")){
            T1 = 0;
        }else{
            T1 = (Integer.parseInt(txt_t1.getText()));
        }
        
        //T2
        if (txt_t2.getText().equals("")){
            T2 = 0;
        }else{
            T2 = (Integer.parseInt(txt_t2.getText()));
        }
        
        //T3
        if (txt_t3.getText().equals("")){
            T3 = 0;
        }else{
            T3 = (Integer.parseInt(txt_t3.getText()));
        }
        
        //T4
        if (txt_t4.getText().equals("")){
            T4 = 0;
        }else{
            T4 = (Integer.parseInt(txt_t4.getText()));
        }
        
       
        Integer Total = T1+T2+T3+T4;
        txt_total.setText(Total.toString());
    }
    
    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        // TODO add your handling code here:
        
        // fazendo a validação dos dados
        if ((txt_ref.getText().isEmpty()) || (jComboBox_nome.getSelectedItem().equals("")) || (txt_maquina.getText().isEmpty()) || (txt_t1.getText().isEmpty()) || (txt_t2.getText().isEmpty())  || (txt_t3.getText().isEmpty())  || (txt_t4.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        }
        else {
        
        BordadoProducaoDTO bordados = new BordadoProducaoDTO();
        bordados.setTurno(jComboBox_turno.getSelectedItem().toString());
        bordados.setMaquina(txt_maquina.getText());
        bordados.setNome(jComboBox_nome.getSelectedItem().toString());
        bordados.setData(txt_data.getText());
        bordados.setCodigo(txt_ref.getText());
        bordados.setCor(jComboBox_cor.getSelectedItem().toString());
        bordados.setPontos(Integer.parseInt(txt_pontos.getText()));
        bordados.setCorte(txt_corte.getText());
        bordados.setT1(Integer.parseInt(txt_t1.getText()));
        bordados.setT2(Integer.parseInt(txt_t2.getText()));
        bordados.setT3(Integer.parseInt(txt_t3.getText()));
        bordados.setT4(Integer.parseInt(txt_t4.getText()));
        bordados.setTotal(Integer.parseInt(txt_total.getText()));
        bordados.setDefeitos(Integer.parseInt(txt_defeitos.getText()));
        bordados.setObs(txt_obs.getText());
        
        
         

            // instanciando a classe ProdutoDAO do pacote dao e criando seu objeto dao

            BordadoProducaoDAO dao = new BordadoProducaoDAO();
            if (dao.adiciona_bordado_producao(bordados)){
                DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
                model.setNumRows(0);
               
                model.addRow(new Object[]{bordados.getId(), bordados.getTurno(), bordados.getMaquina(), bordados.getNome(), bordados.getData(), bordados.getCodigo(), bordados.getCor(), bordados.getPontos(), bordados.getCorte(), bordados.getT1(), bordados.getT2(), bordados.getT3(), bordados.getT4(), bordados.getTotal(), bordados.getDefeitos(), bordados.getObs()});
                
                // apaga os dados preenchidos nos campos de texto
                txt_t1.setText("");
                txt_t2.setText("");
                txt_t3.setText("");
                txt_t4.setText("");
                txt_total.setText("");
                txt_defeitos.setText("0");
                txt_obs.setText("");
                
                
                txt_data.requestFocus();

            }
            else {
                JOptionPane.showMessageDialog(null, "Erro, producao não foi cadastrada! ");
            }
           
        }
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodosActionPerformed
        // TODO add your handling code here:
        
        BordadoProducaoDAO dao = new BordadoProducaoDAO();
       DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
        model.setNumRows(0);
       
        for (BordadoProducaoDTO bordados : dao.listarProducaoBordado()) {
           
            model.addRow(new Object[]{bordados.getId(), bordados.getTurno(), bordados.getMaquina(), bordados.getNome(), bordados.getData(), bordados.getCodigo(), bordados.getCor(), bordados.getPontos(), bordados.getCorte(), bordados.getT1(), bordados.getT2(), bordados.getT3(), bordados.getT4(), bordados.getTotal(), bordados.getDefeitos(), bordados.getObs()});
        }
        //fim listar
        
        
    }//GEN-LAST:event_btnListarTodosActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        // TODO add your handling code here:
         BordadoProducaoDTO bordado = new BordadoProducaoDTO();
                
                Integer linhaSelecionada = -1;
		linhaSelecionada = jTable1.getSelectedRow();
                
            if (linhaSelecionada >= 0) {//se linha selecionada
                
                    Integer id = (Integer) jTable1.getValueAt(linhaSelecionada, 0);
                    String codigo = (String) jTable1.getValueAt(linhaSelecionada, 5);
                    
                    //Confirmação
                    String message = "Deseja realmente excluir producao da ref: "+codigo+" ?";
                    String title = "Confirmação";
                    int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
                    if (reply == JOptionPane.YES_OPTION)
                    {//sim
                            //se confirmou
                            DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
                            bordado.setId(id);//setar o id pra excluir
                            bordado.setCodigo(codigo);
                            BordadoProducaoDAO dao = new BordadoProducaoDAO();
                            if (dao.excluir(bordado)){
                                
                            }
                            else {
                                JOptionPane.showMessageDialog(null, "Erro, a producao de ref : "+codigo+" não foi excluido!");
                            }
                            model.removeRow(linhaSelecionada);
                    }else{
                        //não confirmou
                    }
                 
            }
            else{ //se linha não estiver selecionada
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
            }   // fim linha selecionada
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
        model.setNumRows(0);
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void txt_t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_t1FocusLost
        // TODO add your handling code here:
        if (txt_t1.getText().equals("")){
            txt_t1.setText("0");
        }
        calc_total();
    }//GEN-LAST:event_txt_t1FocusLost

    private void txt_t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_t2FocusLost
        if (txt_t2.getText().equals("")){
            txt_t2.setText("0");
        }
        calc_total();
    }//GEN-LAST:event_txt_t2FocusLost

    private void txt_t3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_t3FocusLost
        if (txt_t3.getText().equals("")){
            txt_t3.setText("0");
        }
        calc_total();
    }//GEN-LAST:event_txt_t3FocusLost

    private void txt_t4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_t4FocusLost
        if (txt_t4.getText().equals("")){
            txt_t4.setText("0");
        }
        calc_total();
    }//GEN-LAST:event_txt_t4FocusLost

    private void btn_CadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_CadastrarFocusGained
        // TODO add your handling code here:
        tdgCTR.reagirEnter(btn_Cadastrar);
    }//GEN-LAST:event_btn_CadastrarFocusGained

    private void txt_defeitosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_defeitosFocusLost
        // TODO add your handling code here:
        if (txt_defeitos.getText().equals("")){
            txt_defeitos.setText("0");
        }
    }//GEN-LAST:event_txt_defeitosFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            java.awt.Desktop.getDesktop().open(new File ("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\produção_bordado.xlsx") );
        } catch (IOException ex) {
            //pau
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BordadoProducaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BordadoProducaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BordadoProducaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BordadoProducaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BordadoProducaoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarTodos;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox_cor;
    private javax.swing.JComboBox jComboBox_nome;
    private javax.swing.JComboBox jComboBox_turno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_corte;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JFormattedTextField txt_data_pesquisar;
    private javax.swing.JTextField txt_defeitos;
    private javax.swing.JTextField txt_maquina;
    private javax.swing.JTextField txt_obs;
    private javax.swing.JTextField txt_pontos;
    private javax.swing.JTextField txt_ref;
    private javax.swing.JTextField txt_t1;
    private javax.swing.JTextField txt_t2;
    private javax.swing.JTextField txt_t3;
    private javax.swing.JTextField txt_t4;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
