/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DTO.EstoqueDTO;
import dao.EstoqueDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import CTR.tdgCTR;
import DTO.CoresDTO;
import DTO.ProdutoDTO;
import dao.CoresDAO;
import dao.ItemPedidoDAO;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;

/**
 *
 * @author PeDr0_HuG0
 */
public class EstoqueCodigoDeBarrasVIEW extends javax.swing.JFrame {

    /**
     * Creates new form EstoqueVIEW
     */
    public EstoqueCodigoDeBarrasVIEW() {
        initComponents();
       //botao x fechar apenas janela
        setDefaultCloseOperation(ProdutoVIEW.HIDE_ON_CLOSE); 
        
       //pegando data atual 
       Date data = new Date(System.currentTimeMillis());    
       SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
       txt_data.setText(formatarDate.format(data));
       
       txt_codigo_barra.requestFocus();
       
       tdgCTR geral = new tdgCTR();
       geral.considerarEnterComoTab(txt_data);
       geral.considerarEnterComoTab(txt_ref);
       //geral.considerarEnterComoTab(jComboBox_Cor);
       geral.considerarEnterComoTab(txt_t1);
       geral.considerarEnterComoTab(txt_t2);
       geral.considerarEnterComoTab(txt_t3);
       geral.considerarEnterComoTab(txt_t4);
           
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ref = new javax.swing.JTextField();
        jLabelT1 = new javax.swing.JLabel();
        txt_t1 = new javax.swing.JTextField();
        jLabelT2 = new javax.swing.JLabel();
        txt_t2 = new javax.swing.JTextField();
        jLabelT3 = new javax.swing.JLabel();
        txt_t3 = new javax.swing.JTextField();
        jLabelT4 = new javax.swing.JLabel();
        txt_t4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Cor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txt_data = new javax.swing.JFormattedTextField();
        btn_Entrada = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        jComboBox_Cores = new javax.swing.JComboBox();
        btn_adiciona = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_Listar = new javax.swing.JButton();
        btn_Limpar_Lista = new javax.swing.JButton();
        txt_data_pesquisar = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ref_pesquisar = new javax.swing.JTextField();
        btn_Pesquisar1 = new javax.swing.JButton();
        btn_Listar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_total_itens = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_codigo_barra = new javax.swing.JTextField();
        txt_tamanho = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_id_cor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_cor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada Estoque"));

        jLabel1.setText("Ref:");

        txt_ref.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_refFocusLost(evt);
            }
        });

        jLabelT1.setText("Tamanho1");

        txt_t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_t1FocusLost(evt);
            }
        });

        jLabelT2.setText("Tamanho2");

        txt_t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_t2FocusLost(evt);
            }
        });

        jLabelT3.setText("Tamanho3");

        txt_t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_t3FocusLost(evt);
            }
        });
        txt_t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_t3KeyPressed(evt);
            }
        });

        jLabelT4.setText("Tamanho4");

        txt_t4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_t4FocusLost(evt);
            }
        });

        jLabel2.setText("Cor:");

        jComboBox_Cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CorActionPerformed(evt);
            }
        });
        jComboBox_Cor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_CorKeyPressed(evt);
            }
        });

        jLabel3.setText("Data:");

        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_Entrada.setText("Entrada");
        btn_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntradaActionPerformed(evt);
            }
        });
        btn_Entrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_EntradaFocusGained(evt);
            }
        });

        jLabel7.setText("Descrição:");
        jLabel7.setFocusable(false);

        txt_descricao.setEnabled(false);
        txt_descricao.setFocusable(false);

        jComboBox_Cores.setFocusable(false);

        btn_adiciona.setText("+");
        btn_adiciona.setFocusable(false);
        btn_adiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionaActionPerformed(evt);
            }
        });

        btn_remove.setText("-");
        btn_remove.setFocusable(false);
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_t1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_t2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_t3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelT4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_t4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_descricao))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_Cores, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_adiciona))))))
                    .addComponent(btn_Entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_Cores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_adiciona)
                        .addComponent(btn_remove))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT1)
                    .addComponent(jLabelT2)
                    .addComponent(jLabelT3)
                    .addComponent(jLabelT4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Entrada))
        );

        txt_t1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_t1.selectAll();
            }
        });
        txt_t2.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_t2.selectAll();
            }
        });
        txt_t3.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_t3.selectAll();
            }
        });
        txt_t4.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_t4.selectAll();
            }
        });
        tdgCTR.todasCores(jComboBox_Cores);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar / Excluir"));

        jLabel5.setText("Data:");

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Listar.setText("Listar Entrada Dia");
        btn_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarActionPerformed(evt);
            }
        });

        btn_Limpar_Lista.setText("Limpar");
        btn_Limpar_Lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Limpar_ListaActionPerformed(evt);
            }
        });

        try {
            txt_data_pesquisar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("REF:");

        btn_Pesquisar1.setText("Pesquisar");
        btn_Pesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Pesquisar1ActionPerformed(evt);
            }
        });

        btn_Listar1.setText("Listar Todas Entradas");
        btn_Listar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Listar1ActionPerformed(evt);
            }
        });

        jButton1.setText("Relatorio Entrada ");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ref_pesquisar)
                    .addComponent(txt_data_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_Pesquisar)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Pesquisar1)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Listar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Excluir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Listar1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_Pesquisar)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Listar)
                    .addComponent(btn_Limpar_Lista)
                    .addComponent(txt_data_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ref_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pesquisar1)
                    .addComponent(jLabel6)
                    .addComponent(btn_Listar1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ENTRADA", "REF", "COR", "T1", "T2", "T3", "T4", "TOTAL", "DESCRICAO"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        //ocultar coluna ID da tabela
        jTable1.getColumnModel().getColumn( 0 ).setMaxWidth( 0 );
        jTable1.getColumnModel().getColumn( 0 ).setMinWidth( 0 );
        jTable1.getTableHeader().getColumnModel().getColumn( 0 ).setMaxWidth( 0 );
        jTable1.getTableHeader().getColumnModel().getColumn( 0 ).setMinWidth( 0 );
        //fim ocultar

        txt_total_itens.setEditable(false);

        jLabel4.setText("Total Itens");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada Estoque por Leitor Codigo de Barras"));

        jLabel8.setText("Leitura codigo:");

        txt_codigo_barra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigo_barraKeyPressed(evt);
            }
        });

        jLabel9.setText("TAMANHO:");

        jLabel10.setText("ID_COR:");

        jLabel11.setText("CODIGO");

        jLabel12.setText("COR:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txt_id_cor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tamanho, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_id_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_itens, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_total_itens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_t3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            if (txt_t4.isEnabled()){
                txt_t4.requestFocus();
            }else{
                //btn_Dividir_Manual.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_t3KeyPressed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        // TODO add your handling code here:
        String data_pesquisar = txt_data_pesquisar.getText();
        listar_estoque_por_data(data_pesquisar);
        
         //total itens
         tdgCTR geral = new tdgCTR();
         txt_total_itens.setText(geral.calc_Total_Itens(jTable1, 8)); 
        
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    public void listar_estoque_por_data(String data_pesquisar){
        if ( (data_pesquisar.equals("  /  /    ")) ){
            JOptionPane.showMessageDialog(null, "Insira uma data!");
            txt_data_pesquisar.requestFocus();
        }else{
        
        EstoqueDAO dao = new EstoqueDAO();
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
       model.setNumRows(0);
       
        for (EstoqueDTO e : dao.getEstoqueDia(data_pesquisar)) {
           
            model.addRow(new Object[]{e.getId(), e.getData_Entrada(), e.getCodigo(), e.getCor(), e.getT1(), e.getT2(), e.getT3(), e.getT4(), e.getTotal(), e.getDescricao()});
        }
        
        }//fim else data!=null
    }//fim listar
    
    
    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        EstoqueDTO estoques = new EstoqueDTO();
        
        Integer linhaSelecionada = -1;
        linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada >= 0) {//se linha selecionada

            Integer id = (Integer) jTable1.getValueAt(linhaSelecionada, 0);
            String ref = (String) jTable1.getValueAt(linhaSelecionada, 2);

            //Confirmação
            String message = "Deseja realmente excluir a ref: "+ref+" ?";
            String title = "Confirmação";
            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION)
            {//sim
                //se confirmou
                DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
                estoques.setId(id);//setar o id pra excluir
                estoques.setCodigo(ref);
                EstoqueDAO dao = new EstoqueDAO();
                if (dao.excluir(estoques)){
                    JOptionPane.showMessageDialog(null, "REF:: "+ref+" excluido com sucesso!");
                    model.removeRow(linhaSelecionada);
                    
                }
                else {
                    JOptionPane.showMessageDialog(null, "Erro, a REF: "+ref+" não foi excluido!");
                }
                
                
               //total itens
                tdgCTR geral = new tdgCTR();
                txt_total_itens.setText(geral.calc_Total_Itens(jTable1, 8)); 
                
            }else{
                //não confirmou
            }

        }
        else{ //se linha não estiver selecionada
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }   // fim linha selecionada
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarActionPerformed
        // TODO add your handling code here:
        //pegando data atual 
       Date data = new Date(System.currentTimeMillis());    
       SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
       
        
        listar_estoque_por_data(formatarDate.format(data));
        
        //total itens
        tdgCTR geral = new tdgCTR();
        txt_total_itens.setText(geral.calc_Total_Itens(jTable1, 8)); 
        
    }//GEN-LAST:event_btn_ListarActionPerformed

    private void btn_Limpar_ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Limpar_ListaActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();

        model.setNumRows(0);
        txt_total_itens.setText("");
        //String[] linha = new String[]{"Pedro", "15" , "Masculino"};
        //model.addRow(linha);
    }//GEN-LAST:event_btn_Limpar_ListaActionPerformed

    private void btn_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntradaActionPerformed
        // TODO add your handling code here:
        //validando campos
        if ((txt_ref.getText().isEmpty()) || (txt_t1.getText().isEmpty()) || (txt_t2.getText().isEmpty()) || (txt_t3.getText().isEmpty()) || (txt_t4.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Complete todos os campos.");
                   
        }
        else {
        
        EstoqueDTO estoque = new EstoqueDTO();
        
        estoque.setData_Entrada(txt_data.getText());
        estoque.setCodigo(txt_ref.getText());
        estoque.setDescricao(txt_descricao.getText());
        estoque.setCor(jComboBox_Cor.getSelectedItem().toString());
        
        Integer t1 = Integer.parseInt(txt_t1.getText());
        Integer t2 = Integer.parseInt(txt_t2.getText());
        Integer t3 = Integer.parseInt(txt_t3.getText());
        Integer t4 = Integer.parseInt(txt_t4.getText());
        
        estoque.setT1(t1);
        estoque.setT2(t2);
        estoque.setT3(t3);
        estoque.setT4(t4);
        
        
        
        //estoque.setCor_original(jComboBox_Cor.getSelectedItem().toString());
        int total = t1+t2+t3+t4;
        estoque.setTotal(total);
        
            EstoqueDAO dao = new EstoqueDAO();
            if (dao.adicionaEstoque(estoque)){
                //listando item pedido adicionado
                    
                    //listando itens do pedido com ID
                    //listar_item_pedido();
                    //uma outra opção é fazer buscar no banco e buscar o last id
                    
                    
                    //adiciona item mas sem o ID
                     DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
                     model.addRow(new Object[]{estoque.getId(),estoque.getData_Entrada(), estoque.getCodigo(), estoque.getCor(), estoque.getT1(), estoque.getT2(), estoque.getT3(), estoque.getT4(), estoque.getTotal(), estoque.getDescricao()});
                     
                     //total itens
                    tdgCTR geral = new tdgCTR();
                    txt_total_itens.setText(geral.calc_Total_Itens(jTable1, 8)); 
                     //total itens
                        //tdgCTR geral = new tdgCTR();
                        //txt_total_itens.setText(Integer.toString(geral.calc_Total_Itens(jTable1, 8)));
                        
                     //limpando campos após adicionar
                     txt_ref.setText("");
                     txt_t1.setText("");
                     txt_t2.setText("");
                     txt_t3.setText("");
                     txt_t4.setText("");
                     jComboBox_Cor.removeAllItems();
                     txt_descricao.setText("");
                     txt_ref.requestFocus();
            }
            else {
                JOptionPane.showMessageDialog(null, "Erro, o item de ref: "+txt_ref.getText()+" não foi adicionado! ");
            }
    
        }//fim else valida
    }//GEN-LAST:event_btn_EntradaActionPerformed

    private void txt_refFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_refFocusLost
        // TODO add your handling code here:
        EstoqueDAO dao = new EstoqueDAO();
        jComboBox_Cor.removeAllItems();
        //pegando dados da referencia inserida

        for (ProdutoDTO p : dao.getCoresCorte(txt_ref.getText())) {
            
            
            //adicionando cores na combobox
            jComboBox_Cor.addItem(p.getCor());
            txt_descricao.setText(p.getDescricao());
        }//fim pegar cores e outros atributos
        
        if (jComboBox_Cor.getSelectedItem()==null){
            //JOptionPane.showMessageDialog(null, "REF "+txt_ref.getText()+" invalido!");
            txt_ref.setText("");
            txt_descricao.setText("");
            txt_ref.requestFocus();
        }
    }//GEN-LAST:event_txt_refFocusLost

    private void btn_EntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_EntradaFocusGained
        // TODO add your handling code here:
        tdgCTR geral = new tdgCTR();
        geral.reagirEnter(btn_Entrada);
    }//GEN-LAST:event_btn_EntradaFocusGained

    private void jComboBox_CorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_CorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            
                txt_t1.requestFocus();
            
        } 
    }//GEN-LAST:event_jComboBox_CorKeyPressed

    
    
    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        
        
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
        //if (model.getRowCount()>0){
            Integer total_itens = 0;
          
            for(int i=0;i<jTable1.getRowCount();i++){ 
               Integer total = (Integer) jTable1.getValueAt(i,8);

               total_itens = total_itens + total;
            }
            System.out.println("Total: "+total_itens);
            txt_total_itens.setText(total_itens.toString());
         
        //}    
       
         
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          
        //total itens
        tdgCTR geral = new tdgCTR();
        txt_total_itens.setText(geral.calc_Total_Itens(jTable1, 8)); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_Pesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Pesquisar1ActionPerformed
        // TODO add your handling code here:

        jTable1.setVisible(true);
        EstoqueDAO dao = new EstoqueDAO();
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();

        model.setNumRows(0);

        for (EstoqueDTO e : dao.getEstoqueEntradaRefID(txt_ref_pesquisar.getText())) {

            model.addRow(new Object[]{e.getId(), e.getData_Entrada(), e.getCodigo(), e.getCor(), e.getT1(), e.getT2(), e.getT3(), e.getT4(), e.getTotal(), e.getDescricao()});
        }

    }//GEN-LAST:event_btn_Pesquisar1ActionPerformed

    private void btn_Listar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Listar1ActionPerformed
        // TODO add your handling code here:
        listar_estoque();
        
        //total itens
        tdgCTR geral = new tdgCTR();
        txt_total_itens.setText(geral.calc_Total_Itens(jTable1, 8));
    }//GEN-LAST:event_btn_Listar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            java.awt.Desktop.getDesktop().open(new File ("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\relatorio_entrada_estoque.xlsx") );
        } catch (IOException ex) {
            //pau
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_t1FocusLost
        // TODO add your handling code here:
        if (txt_t1.getText().equals("")){
            txt_t1.setText("0");
        }
    }//GEN-LAST:event_txt_t1FocusLost

    private void txt_t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_t2FocusLost
        // TODO add your handling code here:
        if (txt_t2.getText().equals("")){
            txt_t2.setText("0");
        }
    }//GEN-LAST:event_txt_t2FocusLost

    private void txt_t3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_t3FocusLost
        // TODO add your handling code here:
        if (txt_t3.getText().equals("")){
            txt_t3.setText("0");
        }
    }//GEN-LAST:event_txt_t3FocusLost

    private void txt_t4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_t4FocusLost
        // TODO add your handling code here:
        if (txt_t4.getText().equals("")){
            txt_t4.setText("0");
        }
    }//GEN-LAST:event_txt_t4FocusLost

    private void btn_adicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionaActionPerformed
        // TODO add your handling code here:
        String cor;
        cor = jComboBox_Cores.getSelectedItem().toString();

        if((jComboBox_Cores.getSelectedItem().equals("-"))){
            JOptionPane.showMessageDialog(null, "Cor invalida, selecione uma cor valida.");
        }else{
            Integer qtd_cor = jComboBox_Cor.getItemCount();//Diminuir 1 por causa do item 0 (TODOS)
            jComboBox_Cor.addItem(cor);
            jComboBox_Cor.setSelectedIndex(qtd_cor);
            jComboBox_Cores.setSelectedIndex(0);
            

        }
    }//GEN-LAST:event_btn_adicionaActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:

        if((jComboBox_Cor.getSelectedItem().equals("TODAS"))){
            JOptionPane.showMessageDialog(null, "A opção 'TODAS' não pode ser removida.");
        }else{

            String cor;
            cor = jComboBox_Cor.getSelectedItem().toString();
            jComboBox_Cor.removeItem(cor);
            jComboBox_Cor.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void jComboBox_CorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_CorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_CorActionPerformed

    private void txt_codigo_barraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigo_barraKeyPressed
        // TODO add your handling code here:
        Integer tamanho_codigo = null;
        String tamanho = null, cor = null, codigo = null;
        if(evt.getKeyCode() == evt.VK_ENTER){
            
            tamanho_codigo = txt_codigo_barra.getText().length();
            
            //PEGANDO TAMANHO
            try {
                tamanho = txt_codigo_barra.getText(tamanho_codigo-1, 1);
                txt_tamanho.setText(tamanho);
            } catch (BadLocationException ex) {
                System.err.println("ERRO AO PEGAR TAMANHO");
            }
            
            //PEGANDO COR
            try {
                cor = txt_codigo_barra.getText(tamanho_codigo-4, 3);
                txt_id_cor.setText(cor);
            } catch (BadLocationException ex) {
                System.err.println("ERRO AO PEGAR cor");
            }
            
            //PEGANDO CODIGO (0 offset, tamanho do codigo - 3(cor e tamanho))
            try {
                codigo = txt_codigo_barra.getText(0,tamanho_codigo-4);
                txt_codigo.setText(codigo);
            } catch (BadLocationException ex) {
                System.err.println("ERRO AO PEGAR codigo");
            }
            
            //******VERIFICAR SE INFORMAÇÕES ESTAO CORRETAS (CODIGO EXISTE E COR EXISTE)
            
            //PEGAR COR DO ID_COR
            //**se banco estiver aberto, nao precisa abrir novamente(FAZER)
            CoresDAO daoCor = new CoresDAO();
            for (CoresDTO c : daoCor.getCor_By_ID(txt_id_cor.getText())) {

                //adicionando cor
                txt_cor.setText(c.getCor());
            }//fim pegar cores e outros atributos
            
            Integer t1 = 0, t2 = 0, t3 = 0, t4 = 0;
            
            switch (tamanho){
                case "1":
                    t1 = 1;
                    break;
                case "2":
                    t2 = 1;
                    break;
                case "3":
                    t3 = 1;
                    break;
                case "4":
                    t4 = 1;
                    break;    
                default:
                    JOptionPane.showMessageDialog(null, "Tamanho Invalido!");
                    return;
            }
            
            //ADICIONANOD ITEM ESTOQUE
                EstoqueDTO estoque = new EstoqueDTO();

                estoque.setData_Entrada(txt_data.getText());
                estoque.setCodigo(txt_codigo.getText());
                //estoque.setDescricao(txt_descricao.getText());
                estoque.setCor(txt_cor.getText());

                estoque.setT1(t1);
                estoque.setT2(t2);
                estoque.setT3(t3);
                estoque.setT4(t4);
                //estoque.setCor_original(jComboBox_Cor.getSelectedItem().toString());
                int total = t1+t2+t3+t4;
                estoque.setTotal(total);


                EstoqueDAO dao = new EstoqueDAO();
            
            if (dao.adicionaEstoque(estoque)){
                
                     DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
                     model.addRow(new Object[]{estoque.getId(),estoque.getData_Entrada(), estoque.getCodigo(), estoque.getCor(), estoque.getT1(), estoque.getT2(), estoque.getT3(), estoque.getT4(), estoque.getTotal(), estoque.getDescricao()});
                     
                     //total itens
                    tdgCTR geral = new tdgCTR();
                    txt_total_itens.setText(geral.calc_Total_Itens(jTable1, 8)); 
                     //total itens
                        //tdgCTR geral = new tdgCTR();
                        //txt_total_itens.setText(Integer.toString(geral.calc_Total_Itens(jTable1, 8)));
                        
                     //limpando campos após adicionar
                     txt_codigo_barra.setText("");
                     txt_codigo.setText("");
                     txt_id_cor.setText("");
                     txt_cor.setText("");
                     txt_tamanho.setText("");
                     txt_codigo_barra.requestFocus();
                     
            }
            else {
                java.awt.Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Erro, o item de ref: "+txt_codigo.getText()+" não foi adicionado! ");
                
            }
            
            
            
            
            
            
            
        } 
    }//GEN-LAST:event_txt_codigo_barraKeyPressed
    
    public void listar_estoque(){
        
        
        EstoqueDAO dao = new EstoqueDAO();
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
       model.setNumRows(0);
       
        for (EstoqueDTO e : dao.getEstoqueEntrada()) {
           
            model.addRow(new Object[]{e.getId(), e.getData_Entrada(), e.getCodigo(), e.getCor(), e.getT1(), e.getT2(), e.getT3(), e.getT4(), e.getTotal(), e.getDescricao()});
        }
        
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueCodigoDeBarrasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueCodigoDeBarrasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueCodigoDeBarrasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueCodigoDeBarrasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueCodigoDeBarrasVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrada;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Limpar_Lista;
    private javax.swing.JButton btn_Listar;
    private javax.swing.JButton btn_Listar1;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Pesquisar1;
    private javax.swing.JButton btn_adiciona;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox_Cor;
    private javax.swing.JComboBox jComboBox_Cores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JLabel jLabelT2;
    private javax.swing.JLabel jLabelT3;
    private javax.swing.JLabel jLabelT4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigo_barra;
    private javax.swing.JTextField txt_cor;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JFormattedTextField txt_data_pesquisar;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_id_cor;
    private javax.swing.JTextField txt_ref;
    private javax.swing.JTextField txt_ref_pesquisar;
    private javax.swing.JTextField txt_t1;
    private javax.swing.JTextField txt_t2;
    private javax.swing.JTextField txt_t3;
    private javax.swing.JTextField txt_t4;
    private javax.swing.JTextField txt_tamanho;
    private javax.swing.JTextField txt_total_itens;
    // End of variables declaration//GEN-END:variables
}
