/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DTO.OrdemCorteDTO;
import dao.OrdemCorteDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PeDr0_HuG0
 */
public class OrdemCorteVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Ordem_de_CorteVIEW
     */
    public OrdemCorteVIEW() {
        initComponents();
        setDefaultCloseOperation(ProdutoVIEW.HIDE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Tipo_Pedido = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_MaisPedidos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_MaisVendidas = new javax.swing.JTable();
        btn_Listar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_data_entrega = new javax.swing.JFormattedTextField();
        jCheckBox_PRIORIDADE = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Cortado = new javax.swing.JTable();
        jRadioButton_div = new javax.swing.JRadioButton();
        jRadioButton_especial = new javax.swing.JRadioButton();
        jRadioButton_todos = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Saldo = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Saldo_Montado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONSULTAR ORDEM DE CORTE");
        setBounds(new java.awt.Rectangle(590, 0, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("REF EM MAIS PEDIDOS"));

        jTable_MaisPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "REF", "QTD_PEDIDOS", "PRIORIDADE"
            }
        ));
        jScrollPane1.setViewportView(jTable_MaisPedidos);
        //ordenando cliacando nas tabelas
        jTable_MaisPedidos.setAutoCreateRowSorter(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("REF MAIS VENDIDAS"));

        jTable_MaisVendidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "REF", "TOTAL VENDIDO", "PRIORIDADE"
            }
        ));
        jScrollPane2.setViewportView(jTable_MaisVendidas);
        if (jTable_MaisVendidas.getColumnModel().getColumnCount() > 0) {
            jTable_MaisVendidas.getColumnModel().getColumn(2).setHeaderValue("PRIORIDADE");
        }
        //ordenando cliacando nas tabelas
        jTable_MaisVendidas.setAutoCreateRowSorter(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        btn_Listar.setText("LISTAR");
        btn_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarActionPerformed(evt);
            }
        });

        jLabel1.setText("DATA DE ENTREGA:");

        try {
            txt_data_entrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jCheckBox_PRIORIDADE.setText("PRIORIDADE");
        jCheckBox_PRIORIDADE.setEnabled(false);
        jCheckBox_PRIORIDADE.setFocusable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("REF CORTADO"));

        jTable_Cortado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "REF", "TOTAL CORTADO"
            }
        ));
        jScrollPane3.setViewportView(jTable_Cortado);
        //ordenando cliacando nas tabelas
        jTable_Cortado.setAutoCreateRowSorter(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        buttonGroup_Tipo_Pedido.add(jRadioButton_div);
        jRadioButton_div.setSelected(true);
        jRadioButton_div.setText("DIV");

        buttonGroup_Tipo_Pedido.add(jRadioButton_especial);
        jRadioButton_especial.setText("ESPECIAL");

        buttonGroup_Tipo_Pedido.add(jRadioButton_todos);
        jRadioButton_todos.setText("TODOS");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("SALDO VENDA - CORTE"));

        jTable_Saldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "REF", "SALDO"
            }
        ));
        jScrollPane4.setViewportView(jTable_Saldo);
        //ordenando cliacando nas tabelas
        jTable_Saldo.setAutoCreateRowSorter(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("SALDO VENDA - MONTADO"));

        jTable_Saldo_Montado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "REF", "SALDO"
            }
        ));
        jScrollPane5.setViewportView(jTable_Saldo_Montado);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton_div)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_especial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_todos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_data_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox_PRIORIDADE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_data_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Listar)
                    .addComponent(jCheckBox_PRIORIDADE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_div)
                    .addComponent(jRadioButton_todos)
                    .addComponent(jRadioButton_especial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jCheckBox_PRIORIDADE.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarActionPerformed
        // TODO add your handling code here:
        String data_entrega = txt_data_entrega.getText();
        
        String tipo_pedido = null;
        
        if ( (data_entrega.equals("  /  /    ")) || (data_entrega==null) ){
            
            if (jRadioButton_div.isSelected()){
                tipo_pedido = "DIVERSOS";
            }else if (jRadioButton_especial.isSelected()){
                tipo_pedido = "ESPECIAL";
            }else{//todos
                tipo_pedido = "TODOS";
            }    
            listar_mais_pedidos(tipo_pedido);
            listar_mais_vendeu(tipo_pedido);
            listar_cortado(tipo_pedido);
            
            
            
            listar_saldo(tipo_pedido);
            listar_saldo_montado(tipo_pedido);
            
            
        }else{
            //com data especificada
            
            if (jRadioButton_div.isSelected()){
               tipo_pedido = "DIVERSOS";
            }else if (jRadioButton_especial.isSelected()){
               tipo_pedido = "ESPECIAL";
            }else{//todos
                tipo_pedido = "TODOS";
                
            }
            
            listar_mais_pedidosData(data_entrega, tipo_pedido);
            listar_mais_vendeuData(data_entrega, tipo_pedido);
            listar_cortadoData(data_entrega, tipo_pedido);
            listar_saldoData(data_entrega, tipo_pedido);
            
            listar_saldoMontadoData(data_entrega, tipo_pedido);
            
            /*
            if (jCheckBox_PRIORIDADE.isSelected()){
                    listar_mais_pedidos_p(data_entrega);
                    listar_mais_vendeuData_p(data_entrega);
                    listar_cortado();
            }else{
                listar_mais_pedidosData(data_entrega);
                listar_mais_vendeuData(data_entrega);
                listar_cortado();
            }
            */
        }//fim data_especificada
    }//GEN-LAST:event_btn_ListarActionPerformed

    public void listar_saldo(String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_Saldo.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getSaldoVendaCorte(tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getTotal()});
        }
        
       
    }//fim listar cortado
    
    public void listar_saldo_montado(String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_Saldo_Montado.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getSaldoVendaMontado(tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getTotal()});
        }
        
       
    }//fim listar saldo montado    
    
    
    public void listar_saldoData(String data_entrega,String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_Saldo.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getSaldoVendaCorte(data_entrega, tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getTotal()});
        }
        
       
    }//fim listar saldo venda - corte
    
    
    public void listar_saldoMontadoData(String data_entrega,String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_Saldo_Montado.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getSaldoVendaMontadoPorData(data_entrega, tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getTotal()});
        }
        
       
    }//fim listar saldo venda - MONTADO
    
     public void listar_mais_pedidos(String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_MaisPedidos.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getMaisPedidos(tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getQtd_pedido()});
        }
        
       
    }//fim listar
    
    
     
     public void listar_mais_pedidosData(String data_entrega, String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_MaisPedidos.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getMaisPedidosData(data_entrega, tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getQtd_pedido()});
        }
        
       
    }//fim listar
    
     //*************PRIORIDADE
     public void listar_mais_pedidos_p(){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_MaisPedidos.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getMaisPedidosP()) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getQtd_pedido(), mp.getPrioridade()});
        }
        
       
    }//fim listar
     
     public void listar_mais_pedidos_p(String data_entrega){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_MaisPedidos.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getMaisPedidosDataP(data_entrega)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getQtd_pedido(), mp.getPrioridade()});
        }
        
       
    }//fim listar
     
//****mais vendeu
     
     public void listar_mais_vendeu(String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_MaisVendidas.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getMaisVendeu(tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getTotal_vendido()});
        }
        
       
    }//fim listar
     
      public void listar_mais_vendeuData(String data_entrega, String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_MaisVendidas.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getMaisVendeuData(data_entrega, tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getTotal_vendido()});
        }
        
       
    }//fim listar
      
      //********PRIORIDADE
      public void listar_mais_vendeu_p(){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_MaisVendidas.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getMaisVendeuP()) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getTotal_vendido(), mp.getPrioridade()});
        }
        
       
    }//fim listar
     
      public void listar_mais_vendeuData_p(String data_entrega){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_MaisVendidas.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getMaisVendeuDataP(data_entrega)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getTotal_vendido(), mp.getPrioridade()});
        }
        
       
    }//fim listar
     
    public void listar_cortado(String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_Cortado.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getCortado(tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getQtd_cortado()});
        }
        
       
    }//fim listar cortado
    
    public void listar_cortadoData(String data_entrega, String tipo_pedido){
        
        
         OrdemCorteDAO dao = new OrdemCorteDAO();
         DefaultTableModel model =  (DefaultTableModel) jTable_Cortado.getModel(); 
            
       model.setNumRows(0);
       
        for (OrdemCorteDTO mp : dao.getCortado(data_entrega, tipo_pedido)) {
           
            model.addRow(new Object[]{mp.getCodigo(), mp.getQtd_cortado()});
        }
        
       
    }//fim listar cortado DATA 
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemCorteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemCorteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemCorteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemCorteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemCorteVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Listar;
    private javax.swing.ButtonGroup buttonGroup_Tipo_Pedido;
    private javax.swing.JCheckBox jCheckBox_PRIORIDADE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton_div;
    private javax.swing.JRadioButton jRadioButton_especial;
    private javax.swing.JRadioButton jRadioButton_todos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable_Cortado;
    private javax.swing.JTable jTable_MaisPedidos;
    private javax.swing.JTable jTable_MaisVendidas;
    private javax.swing.JTable jTable_Saldo;
    private javax.swing.JTable jTable_Saldo_Montado;
    private javax.swing.JFormattedTextField txt_data_entrega;
    // End of variables declaration//GEN-END:variables

    
}
