/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CTR.tdgCTR;
import DTO.ClienteDTO;
import DTO.PedidoDTO;
import dao.ClienteDAO;
import dao.PedidoDAO;
import dao.RelatorioDAO;
import java.awt.Cursor;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PeDr0_HuG0
 */
public class PedidosVIEW extends javax.swing.JFrame {

    /**
     * Creates new form PedidosVIEW
     */
    public PedidosVIEW() {
        initComponents();
       
        txt_n_pedido.requestFocus();
       tdgCTR geral = new tdgCTR();
       geral.considerarEnterComoTab(txt_n_pedido);
       geral.considerarEnterComoTab(txt_codigo_cliente);
       geral.considerarEnterComoTab(txt_data_entrega);
       
        
        ocultar_coluna_tabela();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Itens_Pedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_n_pedido_pesquisar = new javax.swing.JTextField();
        btn_Excluir = new javax.swing.JButton();
        btn_Listar = new javax.swing.JButton();
        btn_Limpar_Lista = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Pesquisar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_relatorio_pedidos = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_n_pedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo_cliente = new javax.swing.JTextField();
        btn_Gerar_N = new javax.swing.JButton();
        btn_Novo_Cliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_Razao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Fantasia = new javax.swing.JTextField();
        btn_Cadastrar_Pedido = new javax.swing.JButton();
        jComboBoxPrioridade = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txt_data_entrega = new javax.swing.JFormattedTextField();
        txt_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_Atualizar = new javax.swing.JButton();
        jCheckBox_Especial = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_n_pedido1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_codigo_cliente1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_Razao1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_Fantasia1 = new javax.swing.JTextField();
        jComboBoxPrioridade1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxStatus1 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txt_data_entrega1 = new javax.swing.JFormattedTextField();
        txt_id1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btn_Atualizar1 = new javax.swing.JButton();
        jCheckBox_Especial1 = new javax.swing.JCheckBox();

        setTitle("Cadastro de Pedidos");

        btn_Itens_Pedido.setText("Cadastrar Itens Pedido");
        btn_Itens_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Itens_PedidoActionPerformed(evt);
            }
        });
        btn_Itens_Pedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_Itens_PedidoKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATA CADASTRO", "CHECK", "Nº PEDIDO", "CODIGO CLIENTE", "DATA ENTREGA", "RAZAO", "FANTASIA", "PRIORIDADE", "STATUS", "TIPO_PEDIDO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        }
        //ordenando cliacando nas tabelas
        jTable1.setAutoCreateRowSorter(true);

        /*COMBOBOX TIPO
        TableColumn tipoCol = jTable1.getColumnModel().getColumn(9);

        JComboBox comboBox_Tipo = new JComboBox();

        comboBox_Tipo.addItem("DIVERSOS");
        comboBox_Tipo.addItem("ESPECIAL");
        tipoCol.setCellEditor(new DefaultCellEditor(comboBox_Tipo));
        //FIM COMBOBOX TIPO
        */

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar / Excluir"));
        jPanel3.setFocusable(false);

        jLabel8.setText("Nº Pedido");

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Listar.setText("Listar Todos");
        btn_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarActionPerformed(evt);
            }
        });

        btn_Limpar_Lista.setText("Limpar");
        btn_Limpar_Lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Limpar_ListaActionPerformed(evt);
            }
        });

        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar Pedidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_relatorio_pedidos.setText("Relatorio Pedidos Checkados");
        btn_relatorio_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relatorio_pedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_n_pedido_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Limpar_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_relatorio_pedidos)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_n_pedido_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Listar)
                    .addComponent(btn_Limpar_Lista)
                    .addComponent(btn_Editar)
                    .addComponent(btn_Pesquisar)
                    .addComponent(jButton2)
                    .addComponent(btn_relatorio_pedidos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Novo Pedido"));

        jLabel1.setText("Nº Pedido:");

        txt_n_pedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_n_pedidoFocusLost(evt);
            }
        });

        jLabel2.setText("Codigo Cliente:");

        txt_codigo_cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigo_clienteFocusLost(evt);
            }
        });

        btn_Gerar_N.setText("Gerar Nº");
        btn_Gerar_N.setFocusable(false);
        btn_Gerar_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Gerar_NActionPerformed(evt);
            }
        });

        btn_Novo_Cliente.setText("Novo Cliente");
        btn_Novo_Cliente.setFocusable(false);
        btn_Novo_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Novo_ClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Entrega:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes Cliente"));

        txt_Razao.setEnabled(false);
        txt_Razao.setFocusable(false);

        jLabel3.setText("Razão Social:");

        jLabel5.setText("Nome Fantasia:");

        txt_Fantasia.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Razao, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(txt_Fantasia))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Razao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btn_Cadastrar_Pedido.setText("Cadastrar Pedido");
        btn_Cadastrar_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cadastrar_PedidoActionPerformed(evt);
            }
        });
        btn_Cadastrar_Pedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_Cadastrar_PedidoFocusGained(evt);
            }
        });

        jComboBoxPrioridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        jComboBoxPrioridade.setFocusable(false);

        jLabel6.setText("Prioridade:");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDENTE", "EXPEDIDO" }));
        jComboBoxStatus.setFocusable(false);

        jLabel7.setText("Status Pedido:");

        try {
            txt_data_entrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_data_entrega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_data_entregaFocusGained(evt);
            }
        });

        txt_id.setEnabled(false);

        jLabel9.setText("ID");

        btn_Atualizar.setText("Atualizar Pedido");
        btn_Atualizar.setEnabled(false);
        btn_Atualizar.setFocusable(false);
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        jCheckBox_Especial.setText("Especial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Cadastrar_Pedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(115, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_codigo_cliente)
                                    .addComponent(jComboBoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_data_entrega)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox_Especial)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_n_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_Novo_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Gerar_N, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Atualizar))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Gerar_N)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox_Especial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_n_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_codigo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Novo_Cliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_data_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cadastrar_Pedido)
                    .addComponent(btn_Atualizar)))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Pedido"));

        jLabel10.setText("Nº Pedido:");

        txt_n_pedido1.setEditable(false);
        txt_n_pedido1.setEnabled(false);
        txt_n_pedido1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_n_pedido1FocusLost(evt);
            }
        });

        jLabel11.setText("Codigo Cliente:");

        txt_codigo_cliente1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigo_cliente1FocusLost(evt);
            }
        });
        txt_codigo_cliente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigo_cliente1KeyPressed(evt);
            }
        });

        jLabel12.setText("Data Entrega:");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes Cliente"));

        txt_Razao1.setEnabled(false);
        txt_Razao1.setFocusable(false);

        jLabel13.setText("Razão Social:");

        jLabel14.setText("Nome Fantasia:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Razao1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(txt_Fantasia1))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_Razao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_Fantasia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jComboBoxPrioridade1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        jComboBoxPrioridade1.setFocusable(false);

        jLabel15.setText("Prioridade:");

        jComboBoxStatus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDENTE", "EXPEDIDO" }));
        jComboBoxStatus1.setFocusable(false);

        jLabel16.setText("Status Pedido:");

        try {
            txt_data_entrega1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txt_id1.setEnabled(false);

        jLabel17.setText("ID");

        btn_Atualizar1.setText("Atualizar Pedido");
        btn_Atualizar1.setFocusable(false);
        btn_Atualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Atualizar1ActionPerformed(evt);
            }
        });

        jCheckBox_Especial1.setText("Especial");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Atualizar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox_Especial1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_n_pedido1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_codigo_cliente1)
                                    .addComponent(jComboBoxStatus1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_data_entrega1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBoxPrioridade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_n_pedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jCheckBox_Especial1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_codigo_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jComboBoxPrioridade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_data_entrega1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btn_Atualizar1))
        );

        jTabbedPane1.addTab("Editar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Itens_Pedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Itens_Pedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Itens_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Itens_PedidoActionPerformed
        // TODO add your handling code here:
        txt_n_pedido.requestFocus();
        new ItemPedidoVIEW().setVisible(true);
        
    }//GEN-LAST:event_btn_Itens_PedidoActionPerformed

    public void ocultar_coluna_tabela(){
        //ocultar coluna ID da tabela
        jTable1.getColumnModel().getColumn( 0 ).setMaxWidth( 0 );  
        jTable1.getColumnModel().getColumn( 0 ).setMinWidth( 0 );  
        jTable1.getTableHeader().getColumnModel().getColumn( 0 ).setMaxWidth( 0 );  
        jTable1.getTableHeader().getColumnModel().getColumn( 0 ).setMinWidth( 0 ); 
        //fim ocultar
    }
    
    private void btn_Gerar_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Gerar_NActionPerformed
        // TODO add your handling code here:
        PedidoDAO dao = new PedidoDAO();
        PedidoDTO pedido = dao.gerar_n_pedido();
        txt_n_pedido.setText(pedido.getN_pedido().toString());
        
        
    }//GEN-LAST:event_btn_Gerar_NActionPerformed

    private void btn_Cadastrar_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cadastrar_PedidoActionPerformed
        // TODO add your handling code here:
       
        // fazendo a validação dos dados
        if ((txt_n_pedido.getText().isEmpty()) || (txt_codigo_cliente.getText().isEmpty()) || (txt_data_entrega.getText().isEmpty()) || (txt_Razao.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        }
        else {

        //pegando data atual 
       Date data = new Date(System.currentTimeMillis());    
       SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
       
         
        PedidoDTO pedidos = new PedidoDTO();
        pedidos.setData_cadastro(formatarDate.format(data));
        pedidos.setN_pedido(Integer.parseInt(txt_n_pedido.getText()));
        pedidos.setCodigo_cliente(Integer.parseInt(txt_codigo_cliente.getText()));
        pedidos.setData_entrega(txt_data_entrega.getText());
        //prioriadade
        pedidos.setPrioriadade(Integer.parseInt(jComboBoxPrioridade.getSelectedItem().toString()));
        //status pedido
        pedidos.setStatus(jComboBoxStatus.getSelectedItem().toString());
        
        pedidos.setRazao(txt_Razao.getText());
        pedidos.setFantasia(txt_Fantasia.getText());
        
        if (jCheckBox_Especial.isSelected()){
            pedidos.setTipo_pedido("ESPECIAL");
        }else{
            pedidos.setTipo_pedido("DIVERSOS");
        }
         

            // instanciando a classe ProdutoDAO do pacote dao e criando seu objeto dao

            PedidoDAO dao = new PedidoDAO();
            if (dao.adiciona_pedido(pedidos)){
                JOptionPane.showMessageDialog(null, "Pedido "+txt_n_pedido.getText()+" adicionado com sucesso! ");
                    
                
                
                
                DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
                model.setNumRows(0);
                model.addRow(new Object[]{pedidos.getId(), pedidos.getData_cadastro(), new Boolean(false), pedidos.getN_pedido(), pedidos.getCodigo_cliente(), pedidos.getData_entrega(), pedidos.getRazao(), pedidos.getFantasia(), pedidos.getPrioriadade(), pedidos.getStatus(), pedidos.getTipo_pedido()});
                    //listando todos pedidos
                   //listar_pedidos();
                     
                    // apaga os dados preenchidos nos campos de texto
                    txt_n_pedido.setText("");
                    txt_codigo_cliente.setText("");
                    txt_data_entrega.setText("");
                    txt_Razao.setText("");
                    txt_Fantasia.setText("");
                    jComboBoxPrioridade.setSelectedIndex(0);
                    jComboBoxStatus.setSelectedIndex(0);
                    jCheckBox_Especial.setSelected(false);

            }
            else {
                JOptionPane.showMessageDialog(null, "Erro, o pedido "+txt_n_pedido.getText()+" não foi cadastrado! ");
            }
           
        }
        
        btn_Itens_Pedido.requestFocus();
    }//GEN-LAST:event_btn_Cadastrar_PedidoActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
                PedidoDTO pedidos = new PedidoDTO();

                                Integer linhaSelecionada = -1;
                                linhaSelecionada = jTable1.getSelectedRow();

                            if (linhaSelecionada >= 0) {//se linha selecionada

                                    Integer id = (Integer) jTable1.getValueAt(linhaSelecionada, 0);
                                    Integer pedido = (Integer) jTable1.getValueAt(linhaSelecionada, 3);

                                    //Confirmação
                                    String message = "Deseja realmente excluir o pedido: "+pedido+" ?";
                                    String title = "Confirmação";
                                    int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
                                    if (reply == JOptionPane.YES_OPTION)
                                    {//sim
                                            //se confirmou
                                            DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
                                            pedidos.setId(id);//setar o id pra excluir
                                            pedidos.setN_pedido(pedido);
                                            PedidoDAO dao = new PedidoDAO();
                                            if (dao.excluir(pedidos)){
                                                JOptionPane.showMessageDialog(null, "Pedido: "+pedido+" excluido com sucesso!");
                                            }
                                            else {
                                                JOptionPane.showMessageDialog(null, "Erro, o pedido: "+pedido+" não foi excluido!");
                                            }
                                            model.removeRow(linhaSelecionada);
                                    }else{
                                        //não confirmou
                                    }

                            }
                            else{ //se linha não estiver selecionada
                            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
                            }   // fim linha selecionada

    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarActionPerformed
        // TODO add your handling code here:

        listar_pedidos();

    }//GEN-LAST:event_btn_ListarActionPerformed

    private void btn_Limpar_ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Limpar_ListaActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();

        model.setNumRows(0);
        //String[] linha = new String[]{"Pedro", "15" , "Masculino"};
        //model.addRow(linha);

    }//GEN-LAST:event_btn_Limpar_ListaActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // TODO add your handling code here:
        
        
        
        
        Integer linhaSelecionada = -1;
        linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada >= 0) {
            Integer id = (Integer) jTable1.getValueAt(linhaSelecionada, 0);

            DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();

            PedidoDAO dao = new PedidoDAO();
            PedidoDTO pedido = dao.getPedidoById(id);

            txt_id1.setText(Integer.toString(pedido.getId()));
            txt_n_pedido1.setText(Integer.toString(pedido.getN_pedido()));
            txt_codigo_cliente1.setText(Integer.toString(pedido.getCodigo_cliente()));
            txt_Razao1.setText(pedido.getRazao());
            txt_Fantasia1.setText(pedido.getFantasia());
            
            //formatando retorno data do banco
            //criei novo campo no DTO do tipo data
            SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");
            txt_data_entrega1.setText(formatarData.format(pedido.getData()));
            //converter prioridade para string para aparecer no jcombobox
            jComboBoxPrioridade1.setSelectedItem(pedido.getPrioriadade().toString());
            jComboBoxStatus1.setSelectedItem(pedido.getStatus());
            
            String especial = pedido.getTipo_pedido();
            
            if (especial.equals("ESPECIAL")){
                jCheckBox_Especial1.setSelected(true);
            }else{
                jCheckBox_Especial1.setSelected(false);
            }
            
            jTabbedPane1.setSelectedIndex(1);
            txt_codigo_cliente1.requestFocus();
            
        } else {
            JOptionPane.showMessageDialog(null, "É necesário selecionar uma linha. Clique em Listar e selecione!");
        }

        
        
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        // TODO add your handling code here:
       String n_pedido = txt_n_pedido_pesquisar.getText();
       if (existe_pedido(n_pedido)){ //se existir = listar
           listar_pedidoX(n_pedido);
       }else{
           //não existe pedido
       }
       

    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void txt_codigo_clienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigo_clienteFocusLost

        
    }//GEN-LAST:event_txt_codigo_clienteFocusLost

    private void btn_Novo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Novo_ClienteActionPerformed
        // TODO add your handling code here:
        new ClienteVIEW().setVisible(true);
    }//GEN-LAST:event_btn_Novo_ClienteActionPerformed

    private void txt_n_pedidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_n_pedidoFocusLost
        // TODO add your handling code here:
        String n_pedido = txt_n_pedido.getText();
        if (existe_pedido2(n_pedido)){ //se existir = listar
           listar_pedidoX(n_pedido);
           JOptionPane.showMessageDialog(null, "Nº Pedido já existe");
           txt_n_pedido.setText("");
           txt_n_pedido.requestFocus();
           
       }else{
           //não existe pedido
       }
    }//GEN-LAST:event_txt_n_pedidoFocusLost

    private void txt_data_entregaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_data_entregaFocusGained
        // TODO add your handling code here:
                
        //consultando cliente para preencher formulario
        
        //esvaziando campos
        txt_Razao.setText("");
        txt_Fantasia.setText("");
        
        
        String codigo_cliente = txt_codigo_cliente.getText();
        
          jTable1.setVisible(true);
       ClienteDAO dao = new ClienteDAO();
       DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
       model.setNumRows(0);
       
        for (ClienteDTO c : dao.getClientePorCodigo(codigo_cliente)) {
             txt_Razao.setText(c.getRazao());
             txt_Fantasia.setText(c.getFantasia());
        }
        
        if ((txt_Razao.getText().isEmpty()) ){
                    txt_codigo_cliente.requestFocus();
                    txt_codigo_cliente.setText("");
                    JOptionPane.showMessageDialog(null, "Cliente não existe.");
                    
                    
        }
        
        
    }//GEN-LAST:event_txt_data_entregaFocusGained

    private void btn_Cadastrar_PedidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_Cadastrar_PedidoFocusGained
        // TODO add your handling code here:
        tdgCTR geral = new tdgCTR();
        geral.reagirEnter(btn_Cadastrar_Pedido);
        
    }//GEN-LAST:event_btn_Cadastrar_PedidoFocusGained

    private void btn_Itens_PedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_Itens_PedidoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            txt_n_pedido.requestFocus();
           new ItemPedidoVIEW().setVisible(true);
        } 
    }//GEN-LAST:event_btn_Itens_PedidoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ConsultarPedidosVIEW().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
        PedidoDTO pedido = new PedidoDTO();

        if (txt_id.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha e clique em editar!");
        }
        else{

            pedido.setId(Integer.parseInt(txt_id.getText()));
            pedido.setN_pedido(Integer.parseInt(txt_n_pedido.getText()));
            pedido.setCodigo_cliente(Integer.parseInt(txt_codigo_cliente.getText()));
            pedido.setRazao(txt_Razao.getText());
            pedido.setFantasia(txt_Fantasia.getText());

            pedido.setData_entrega(txt_data_entrega.getText());
            pedido.setPrioriadade(Integer.parseInt(jComboBoxPrioridade.getSelectedItem().toString()));
            pedido.setStatus(jComboBoxStatus.getSelectedItem().toString());

            // fazendo a validação dos dados
            if ((txt_n_pedido.getText().isEmpty()) || (txt_codigo_cliente.getText().isEmpty()) || (txt_data_entrega.getText().isEmpty()) || (txt_Razao.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
            }
            else {
                // instanciando a classe ProdutoDAO do pacote dao e criando seu objeto dao

                PedidoDAO dao = new PedidoDAO();
                if (dao.alterar(pedido)){
                    JOptionPane.showMessageDialog(null, "Pedido "+txt_n_pedido.getText()+" alterado com sucesso! ");

                    // apaga os dados preenchidos nos campos de texto
                    txt_id.setText("");
                    txt_n_pedido.setText("");
                    txt_codigo_cliente.setText("");
                    txt_data_entrega.setText("00/00/0000");
                    txt_Razao.setText("");
                    txt_Fantasia.setText("");
                    jComboBoxPrioridade.setSelectedIndex(0);
                    jComboBoxStatus.setSelectedIndex(0);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Erro, o pedido "+txt_n_pedido.getText()+" não foi alterado!");
                }

            }

        }
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_Atualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Atualizar1ActionPerformed
        // TODO add your handling code here:
        
        //setando cliente
        
        if ((txt_n_pedido1.getText().isEmpty()) || (txt_codigo_cliente1.getText().isEmpty()) || (txt_data_entrega1.getText().isEmpty()) ) {
                JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
            }
            else {
        
        
        
        txt_Razao1.setText("");
        txt_Fantasia1.setText("");
        
        
        String codigo_cliente = txt_codigo_cliente1.getText();
        
       jTable1.setVisible(true);
       ClienteDAO daoCli = new ClienteDAO();
       DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
       
       
        for (ClienteDTO c : daoCli.getClientePorCodigo(codigo_cliente)) {
             txt_Razao1.setText(c.getRazao());
             txt_Fantasia1.setText(c.getFantasia());
        }
        
        if ((txt_Razao1.getText().isEmpty()) ){
                    txt_codigo_cliente1.requestFocus();
                    txt_codigo_cliente1.setText("");
                    //cliente nao existe
                    
                    
        }
        
        
        
        //fim setando cliente
        
        //atualizando pedidos
        PedidoDTO pedido = new PedidoDTO();

        if (txt_id1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha e clique em editar!");
        }
        else{

            pedido.setId(Integer.parseInt(txt_id1.getText()));
            pedido.setN_pedido(Integer.parseInt(txt_n_pedido1.getText()));
            pedido.setCodigo_cliente(Integer.parseInt(txt_codigo_cliente1.getText()));
            pedido.setRazao(txt_Razao1.getText());
            pedido.setFantasia(txt_Fantasia1.getText());

            pedido.setData_entrega(txt_data_entrega1.getText());
            pedido.setPrioriadade(Integer.parseInt(jComboBoxPrioridade1.getSelectedItem().toString()));
            pedido.setStatus(jComboBoxStatus1.getSelectedItem().toString());
            
            if (jCheckBox_Especial1.isSelected()){
                pedido.setTipo_pedido("ESPECIAL");
            }else{
                pedido.setTipo_pedido("DIVERSOS");
            }

            // fazendo a validação dos dados
            if ((txt_n_pedido1.getText().isEmpty()) || (txt_codigo_cliente1.getText().isEmpty()) || (txt_data_entrega1.getText().isEmpty()) || (txt_Razao1.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
            }
            else {
                // instanciando a classe ProdutoDAO do pacote dao e criando seu objeto dao

                PedidoDAO dao = new PedidoDAO();
                if (dao.alterar(pedido)){
                    JOptionPane.showMessageDialog(null, "Pedido "+txt_n_pedido1.getText()+" alterado com sucesso! ");
                    
                    String n_pedido = txt_n_pedido1.getText();
                    listar_pedidoX(n_pedido);
                    // apaga os dados preenchidos nos campos de texto
                    txt_id1.setText("");
                    txt_n_pedido1.setText("");
                    txt_codigo_cliente1.setText("");
                    txt_data_entrega1.setText("00/00/0000");
                    txt_Razao1.setText("");
                    txt_Fantasia1.setText("");
                    jComboBoxPrioridade1.setSelectedIndex(0);
                    jComboBoxStatus1.setSelectedIndex(0);
                    jCheckBox_Especial1.setSelected(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Erro, o pedido "+txt_n_pedido1.getText()+" não foi alterado!");
                }

            }

        }
        
        }//fim validar
    }//GEN-LAST:event_btn_Atualizar1ActionPerformed

    private void txt_codigo_cliente1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigo_cliente1FocusLost
        // TODO add your handling code here:
        //esvaziando campos
        txt_Razao1.setText("");
        txt_Fantasia1.setText("");
        
        
        String codigo_cliente = txt_codigo_cliente1.getText();
        
       jTable1.setVisible(true);
       ClienteDAO dao = new ClienteDAO();
       DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
       
       
        for (ClienteDTO c : dao.getClientePorCodigo(codigo_cliente)) {
             txt_Razao1.setText(c.getRazao());
             txt_Fantasia1.setText(c.getFantasia());
        }
        
        if ((txt_Razao1.getText().isEmpty()) ){
                    
                    txt_codigo_cliente1.setText("");
                    //cliente nao existe
                    
                    
        }
    }//GEN-LAST:event_txt_codigo_cliente1FocusLost

    private void txt_n_pedido1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_n_pedido1FocusLost
        // TODO add your handling code here:
        String n_pedido = txt_n_pedido1.getText();
        if (existe_pedido2(n_pedido)){ //se existir = listar
           listar_pedidoX(n_pedido);
           
           
       }else{
           //não existe pedido
            JOptionPane.showMessageDialog(null, "Nº Pedido não existe");
           txt_n_pedido1.setText("");
           
       }
    }//GEN-LAST:event_txt_n_pedido1FocusLost

    private void txt_codigo_cliente1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigo_cliente1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_codigo_cliente1KeyPressed

    private void btn_relatorio_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relatorio_pedidosActionPerformed
        // TODO add your handling code here:
        
        Boolean calcular;
        //Integer id;
        Integer pedidos;
        
        
        String todos_n_pedidos = null;
        
        int x = 0;

        for(int i=0;i<jTable1.getRowCount();i++){ 
            calcular = (Boolean) jTable1.getValueAt(i, 2);
            if ((calcular != null) && (calcular != false)){//só executa se não for nulo ou estar selecionado
                System.err.println("Situacao calcular: "+calcular.toString());
                //SE ESTIVER SELECIONADO
                if (calcular == true){
                    
                    //id = (Integer) jTable1.getValueAt(i, 0);
                    pedidos = (Integer) jTable1.getValueAt(i, 3);
                                        
                    if (x==0){
                        todos_n_pedidos = pedidos.toString();
                        
                    }else{
                        todos_n_pedidos = todos_n_pedidos+", "+pedidos.toString();
                    }
                    
                    
                    System.out.println("Todos os n_pedidos: "+todos_n_pedidos);
                    x++;
                    
                    
                    
                }else{
                }//fim selecionado
            
            }//fim SE 
                

        }//fim row count (verificou a tabela inteira)
                                    
        //fazendo relatorio
        HashMap parametros = new HashMap();  
        RelatorioDAO dao = new RelatorioDAO();
        
        String tipo_pedido = "DIVERSOS";
        parametros.put("tipo_pedido", tipo_pedido);
        parametros.put("todos_n_pedidos", todos_n_pedidos);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        JRResultSetDataSource jrRS = new JRResultSetDataSource(dao.relatorio_vendas_n_pedidos(tipo_pedido, todos_n_pedidos));  
        JasperPrint jasperPrint;  
       
        try {  
            //PEGANDO DO DIRETORIO MAZIN
            //jasperPrint = JasperFillManager.fillReport("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\n_pedido.jasper" , parametros, jrRS);  
            
            
            InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/relatorio_vendas_pedidos_selecionados.jasper" );
            jasperPrint = JasperFillManager.fillReport(inputStream, parametros, jrRS);  
            JasperViewer.viewReport(jasperPrint, false);  
        } catch (JRException ex) {  
            JOptionPane.showMessageDialog(null, ex);  
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
        
        
    }//GEN-LAST:event_btn_relatorio_pedidosActionPerformed
    
     //verificar se o Pedido2 X já existe
    public boolean existe_pedido2(String n_pedido){
            
        PedidoDAO dao = new PedidoDAO();
        try {
            if (dao.temPedido(n_pedido)){
                return true;
            }
            else {
                return false;
            }
        } catch (SQLException ex) {
            System.out.println("Erro ao verificar");
            System.err.println(ex.getMessage());
        }
        return false;
    }
    
    //verificar se o Pedido X já existe
    public boolean existe_pedido(String n_pedido){
         
        PedidoDAO dao = new PedidoDAO();
        try {
            if (dao.temPedido(n_pedido)){
                return true;
            }
            else {
                JOptionPane.showMessageDialog(null, "Nº Pedido não existe");
                return false;
            }
        } catch (SQLException ex) {
            System.out.println("Erro ao verificar");
            System.err.println(ex.getMessage());
        }
        
        return false;
    }
    
    public void listar_pedidoX(String n_pedido){
        
        
       PedidoDAO dao = new PedidoDAO();
       DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
        model.setNumRows(0);
       
        for (PedidoDTO pedidos : dao.getPedidoX(n_pedido, "TODOS")) {
            
           if (pedidos.getId()!=null){
           
           model.addRow(new Object[]{pedidos.getId(), pedidos.getData_cadastro(),new Boolean(false), pedidos.getN_pedido(), pedidos.getCodigo_cliente(), pedidos.getData_entrega(), pedidos.getRazao(), pedidos.getFantasia(), pedidos.getPrioriadade(), pedidos.getStatus(), pedidos.getTipo_pedido()});
           }
           else{
               
               JOptionPane.showMessageDialog(null, "Pedido não existe.");
           }
           
        }
        //fim listar
    }
    
     public void listar_pedidos(){
        
        
       PedidoDAO dao = new PedidoDAO();
       DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
        model.setNumRows(0);
       
        for (PedidoDTO pedidos : dao.listarPedidos()) {
           
            model.addRow(new Object[]{pedidos.getId(), pedidos.getData_cadastro(),new Boolean(false), pedidos.getN_pedido(), pedidos.getCodigo_cliente(), pedidos.getData_entrega(), pedidos.getRazao(), pedidos.getFantasia(), pedidos.getPrioriadade(), pedidos.getStatus(), pedidos.getTipo_pedido()});
        }
        //fim listar
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidosVIEW().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atualizar;
    private javax.swing.JButton btn_Atualizar1;
    private javax.swing.JButton btn_Cadastrar_Pedido;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Gerar_N;
    private javax.swing.JButton btn_Itens_Pedido;
    private javax.swing.JButton btn_Limpar_Lista;
    private javax.swing.JButton btn_Listar;
    private javax.swing.JButton btn_Novo_Cliente;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_relatorio_pedidos;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox_Especial;
    private javax.swing.JCheckBox jCheckBox_Especial1;
    private javax.swing.JComboBox jComboBoxPrioridade;
    private javax.swing.JComboBox jComboBoxPrioridade1;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JComboBox jComboBoxStatus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_Fantasia;
    private javax.swing.JTextField txt_Fantasia1;
    private javax.swing.JTextField txt_Razao;
    private javax.swing.JTextField txt_Razao1;
    private javax.swing.JTextField txt_codigo_cliente;
    private javax.swing.JTextField txt_codigo_cliente1;
    private javax.swing.JFormattedTextField txt_data_entrega;
    private javax.swing.JFormattedTextField txt_data_entrega1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_n_pedido;
    private javax.swing.JTextField txt_n_pedido1;
    private javax.swing.JTextField txt_n_pedido_pesquisar;
    // End of variables declaration//GEN-END:variables
}
