/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;
//lawww
import static VIEW.TDG_SIS_VIEW.banco_selecionado;
import dao.RelatorioDAO;
import java.awt.Cursor;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.poi.hssf.usermodel.HeaderFooter;
import org.joda.time.DateTimeZone;
import org.joda.time.LocalDate;

/**
 *
 * @author PeDr0_HuG0
 */
public class PrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalVIEW() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        System.err.println("Coleção: "+TDG_SIS_VIEW.banco_selecionado);
        this.setTitle("TDG - "+TDG_SIS_VIEW.banco_selecionado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Produto = new javax.swing.JButton();
        btn_Pedidos = new javax.swing.JButton();
        btn_Itens_Pedido = new javax.swing.JButton();
        btn_Cliente = new javax.swing.JButton();
        btn_Espedicao = new javax.swing.JButton();
        btn_Entrada_Estoque = new javax.swing.JButton();
        btn_Corte = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_Ordem_Corte = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_Consumo_Malha = new javax.swing.JButton();
        btn_Producao_Bordado = new javax.swing.JButton();
        btn_Etq_Codigo_Barras = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_Corte1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Item_Pedido = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Produto.setText("Cadastro de Produto");
        btn_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProdutoActionPerformed(evt);
            }
        });

        btn_Pedidos.setText("Cadastro de Pedidos");
        btn_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PedidosActionPerformed(evt);
            }
        });

        btn_Itens_Pedido.setText("Itens Pedido");
        btn_Itens_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Itens_PedidoActionPerformed(evt);
            }
        });

        btn_Cliente.setText("Cadastro de Cliente");
        btn_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteActionPerformed(evt);
            }
        });

        btn_Espedicao.setText("Expedição");
        btn_Espedicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EspedicaoActionPerformed(evt);
            }
        });

        btn_Entrada_Estoque.setText("Entrada Estoque");
        btn_Entrada_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Entrada_EstoqueActionPerformed(evt);
            }
        });

        btn_Corte.setText("Corte");
        btn_Corte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CorteActionPerformed(evt);
            }
        });

        jButton1.setText("Consultar Estoque");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_Ordem_Corte.setText("Consultar Ordem de Corte");
        btn_Ordem_Corte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ordem_CorteActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar Pedidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Processos Produção");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Etiquetas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_Consumo_Malha.setText("Consumo Malha");
        btn_Consumo_Malha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Consumo_MalhaActionPerformed(evt);
            }
        });

        btn_Producao_Bordado.setText("Producao Bordado");
        btn_Producao_Bordado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Producao_BordadoActionPerformed(evt);
            }
        });

        btn_Etq_Codigo_Barras.setText("Etiquetas (Codigo de Barras)");
        btn_Etq_Codigo_Barras.setEnabled(false);
        btn_Etq_Codigo_Barras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Etq_Codigo_BarrasActionPerformed(evt);
            }
        });

        jButton7.setText("Pedidos Malha");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Gerenciar Cores");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setText("Estoque Codigo Barras");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btn_Corte1.setText("Infesto Corte");
        btn_Corte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Corte1ActionPerformed(evt);
            }
        });

        jButton9.setText("testes");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setText("Ficha Tecnica");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastros");
        jMenu1.setIconTextGap(10);

        jMenuItem1.setText("Produto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Pedidos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Itens Pedido");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem5.setText("Entrada Estoque");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Corte");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Ações");
        jMenu4.setIconTextGap(10);

        jMenuItem10.setText("Expedir Pedido");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Consultar");
        jMenu3.setIconTextGap(10);

        jMenuItem7.setText("Estoque");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Ordem de Corte");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem12.setText("Consultar Pedidos");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem11.setText("Processos Produção");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem16.setText("Processos Etiquetas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Relatorios");
        jMenu2.setEnabled(false);
        jMenu2.setIconTextGap(10);

        jMenuItem_Item_Pedido.setText("Pedido (Itens)");
        jMenuItem_Item_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Item_PedidoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Item_Pedido);

        jMenuItem13.setText("Entrada Estoque");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Vendas Diversos");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Vendas Especiais");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem9.setText("Vendas Geral");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem17.setText("Produção Bordado");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuBar1.add(jMenu2);
        jMenu2.setVisible(false);

        jMenu5.setText("Relatorios");
        jMenu5.setIconTextGap(10);

        jMenuItem18.setText("Pedido (Itens)");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuItem19.setText("Vendas Diversos");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem19);

        jMenuItem20.setText("Vendas Especial");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem20);

        jMenuItem21.setText("Vendas Geral");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem21);

        jMenuItem22.setText("Fechamento");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem22);

        jMenuItem23.setText("Produtos");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem23);
        jMenu5.add(jSeparator2);

        jMenuItem26.setText("Diversos com Data");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem26);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Funcionarios");

        jMenuItem24.setText("Cadastrar");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem24);

        jMenuItem25.setText("Banco de Horas");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem25);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Corte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Espedicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Corte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Pedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Entrada_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Producao_Bordado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Ordem_Corte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Consumo_Malha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Itens_Pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Etq_Codigo_Barras)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Produto)
                    .addComponent(btn_Pedidos)
                    .addComponent(btn_Itens_Pedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cliente)
                    .addComponent(jButton2)
                    .addComponent(jButton8)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Entrada_Estoque)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Espedicao)
                    .addComponent(btn_Producao_Bordado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Corte)
                    .addComponent(btn_Ordem_Corte)
                    .addComponent(jButton4)
                    .addComponent(btn_Etq_Codigo_Barras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btn_Consumo_Malha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(btn_Corte1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProdutoActionPerformed
        // TODO add your handling code here:
        new ProdutoVIEW().setVisible(true);
    }//GEN-LAST:event_btn_ProdutoActionPerformed

    private void btn_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PedidosActionPerformed
        // TODO add your handling code here:
        new PedidosVIEW().setVisible(true);
    }//GEN-LAST:event_btn_PedidosActionPerformed

    private void btn_Itens_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Itens_PedidoActionPerformed
        // TODO add your handling code here:
        new ItemPedidoVIEW().setVisible(true);
    }//GEN-LAST:event_btn_Itens_PedidoActionPerformed

    private void btn_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteActionPerformed
        // TODO add your handling code here:
        new ClienteVIEW().setVisible(true);
    }//GEN-LAST:event_btn_ClienteActionPerformed

    private void btn_EspedicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EspedicaoActionPerformed
        // TODO add your handling code here:
        new ExpedicaoVIEW().setVisible(true);
    }//GEN-LAST:event_btn_EspedicaoActionPerformed

    private void btn_Entrada_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Entrada_EstoqueActionPerformed
        // TODO add your handling code here:
        new EstoqueVIEW().setVisible(true);
    }//GEN-LAST:event_btn_Entrada_EstoqueActionPerformed

    private void btn_CorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CorteActionPerformed
        // TODO add your handling code here:
        new CorteVIEW().setVisible(true);
    }//GEN-LAST:event_btn_CorteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ConsultarEstoqueVIEW().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_Ordem_CorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ordem_CorteActionPerformed
        // TODO add your handling code here:
        new OrdemCorteVIEW().setVisible(true);
    }//GEN-LAST:event_btn_Ordem_CorteActionPerformed

    private void jMenuItem_Item_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Item_PedidoActionPerformed
        // TODO add your handling code here:
        //String caminho = getClass().getClassLoader().getResource("C:\\relatorio_tdg").getPath();  
        try {
            // TODO add your handling code here:
            
            java.awt.Desktop.getDesktop().open(new File ("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\relatorio_pedidos.xlsx") );
        } catch (IOException ex) {
            //pau
        }
    }//GEN-LAST:event_jMenuItem_Item_PedidoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ProdutoVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new ClienteVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new PedidosVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new ItemPedidoVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new EstoqueVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new CorteVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new ConsultarEstoqueVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new OrdemCorteVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            
            java.awt.Desktop.getDesktop().open(new File ("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\relatorio_vendas_geral.xlsx") );
        } catch (IOException ex) {
            //pau
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         new ExpedicaoVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ConsultarPedidosVIEW().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new ConsultarPedidosVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new ProducaoVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new ProducaoVIEW().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            java.awt.Desktop.getDesktop().open(new File ("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\relatorio_entrada_estoque.xlsx") );
        } catch (IOException ex) {
            //pau
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            java.awt.Desktop.getDesktop().open(new File ("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\relatorio_vendas_diversos.xlsx") );
        } catch (IOException ex) {
            //pau
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            java.awt.Desktop.getDesktop().open(new File ("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\relatorio_vendas_especial.xlsx") );
        } catch (IOException ex) {
            //pau
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
         new EtiquetaVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new EtiquetaVIEW().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_Consumo_MalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Consumo_MalhaActionPerformed
        // TODO add your handling code here:
        new MalhaConsumoVIEW().setVisible(true);
    }//GEN-LAST:event_btn_Consumo_MalhaActionPerformed

    private void btn_Producao_BordadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Producao_BordadoActionPerformed
        // TODO add your handling code here:
        new BordadoProducaoVIEW().setVisible(true);
    }//GEN-LAST:event_btn_Producao_BordadoActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            java.awt.Desktop.getDesktop().open(new File ("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\produção_bordado.xlsx") );
        } catch (IOException ex) {
            //pau
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void btn_Etq_Codigo_BarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Etq_Codigo_BarrasActionPerformed
        // TODO add your handling code here:
        new EtiquetaCodigoBarraVIEW().setVisible(true);
    }//GEN-LAST:event_btn_Etq_Codigo_BarrasActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        HashMap parametros = new HashMap();  
        RelatorioDAO dao = new RelatorioDAO();
        String n_pedido = JOptionPane.showInputDialog(null, "Insira o nº do pedido: ");
        
        parametros.put("n_pedido", n_pedido);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        JRResultSetDataSource jrRS = new JRResultSetDataSource(dao.listarPedido(n_pedido));  
        JasperPrint jasperPrint;  
       
        try {  
            //PEGANDO DO DIRETORIO MAZIN
            //jasperPrint = JasperFillManager.fillReport("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\n_pedido.jasper" , parametros, jrRS);  
            
            
            InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/n_pedido.jasper" );
            //InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/n_pedido_loja.jasper" );
            jasperPrint = JasperFillManager.fillReport(inputStream, parametros, jrRS);  
            JasperViewer.viewReport(jasperPrint, false);  
        } catch (JRException ex) {  
            JOptionPane.showMessageDialog(null, ex);  
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));  
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        HashMap parametros = new HashMap();  
        RelatorioDAO dao = new RelatorioDAO();
        
        String tipo_pedido = "DIVERSOS";
        parametros.put("tipo_pedido", tipo_pedido);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        JRResultSetDataSource jrRS = new JRResultSetDataSource(dao.relatorio_vendas(tipo_pedido));  
        JasperPrint jasperPrint;  
       
        try {  
            //PEGANDO DO DIRETORIO MAZIN
            //jasperPrint = JasperFillManager.fillReport("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\n_pedido.jasper" , parametros, jrRS);  
            
            
            InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/relatorio_vendas_montado.jasper" );
            jasperPrint = JasperFillManager.fillReport(inputStream, parametros, jrRS);  
            JasperViewer.viewReport(jasperPrint, false);  
        } catch (JRException ex) {  
            JOptionPane.showMessageDialog(null, ex);  
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        HashMap parametros = new HashMap();  
        RelatorioDAO dao = new RelatorioDAO();
        //String tipo_pedido = JOptionPane.showInputDialog(null, "Insira o tipo do pedido da consulta: ");
        String tipo_pedido = "GERAL";
        parametros.put("tipo_pedido", tipo_pedido);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        JRResultSetDataSource jrRS = new JRResultSetDataSource(dao.relatorio_vendas("%"));  
        JasperPrint jasperPrint;  
       
        try {  
            //PEGANDO DO DIRETORIO MAZIN
            //jasperPrint = JasperFillManager.fillReport("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\n_pedido.jasper" , parametros, jrRS);  
            
            
            InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/relatorio_vendas_montado.jasper" );
            jasperPrint = JasperFillManager.fillReport(inputStream, parametros, jrRS);  
            JasperViewer.viewReport(jasperPrint, false);  
        } catch (JRException ex) {  
            JOptionPane.showMessageDialog(null, ex);  
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        HashMap parametros = new HashMap();  
        RelatorioDAO dao = new RelatorioDAO();
        //String tipo_pedido = JOptionPane.showInputDialog(null, "Insira o tipo do pedido da consulta: ");
        String tipo_pedido = "ESPECIAL";
        parametros.put("tipo_pedido", tipo_pedido);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        JRResultSetDataSource jrRS = new JRResultSetDataSource(dao.relatorio_vendas(tipo_pedido));  
        JasperPrint jasperPrint;  
       
        try {  
            //PEGANDO DO DIRETORIO MAZIN
            //jasperPrint = JasperFillManager.fillReport("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\n_pedido.jasper" , parametros, jrRS);  
            
            
            InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/relatorio_vendas_montado.jasper" );
            jasperPrint = JasperFillManager.fillReport(inputStream, parametros, jrRS);  
            JasperViewer.viewReport(jasperPrint, false);  
        } catch (JRException ex) {  
            JOptionPane.showMessageDialog(null, ex);  
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        HashMap parametros = new HashMap();  
        RelatorioDAO dao = new RelatorioDAO();
        //String tipo_pedido = JOptionPane.showInputDialog(null, "Insira o tipo do pedido da consulta: ");
        
        parametros.put("colecao", TDG_SIS_VIEW.banco_selecionado.toString());
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        JRResultSetDataSource jrRS = new JRResultSetDataSource(dao.relatorio_produtos());  
        JasperPrint jasperPrint;  
       
        try {  
            //PEGANDO DO DIRETORIO MAZIN
            //jasperPrint = JasperFillManager.fillReport("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\n_pedido.jasper" , parametros, jrRS);  
            
            
            InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/fechamento_produtos.jasper" );
            jasperPrint = JasperFillManager.fillReport(inputStream, parametros, jrRS);  
            JasperViewer.viewReport(jasperPrint, false);  
        } catch (JRException ex) {  
            JOptionPane.showMessageDialog(null, ex);  
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new MalhaPedidosVIEW().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new CoresVIEW().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new EstoqueCodigoDeBarrasVIEW().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_Corte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Corte1ActionPerformed
        // TODO add your handling code here:
        new CorteInfestoVIEW().setVisible(true);
    }//GEN-LAST:event_btn_Corte1ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        HashMap parametros = new HashMap();  
        RelatorioDAO dao = new RelatorioDAO();
        
        //parametros.put("colecao", banco_selecionado);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        JRResultSetDataSource jrRS = new JRResultSetDataSource(dao.relatorio_produtos());  
        JasperPrint jasperPrint;  
       
        try {  
            //PEGANDO DO DIRETORIO MAZIN
            //jasperPrint = JasperFillManager.fillReport("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\n_pedido.jasper" , parametros, jrRS);  
            
            
            InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/produtos.jasper" );
            jasperPrint = JasperFillManager.fillReport(inputStream, parametros, jrRS);  
            JasperViewer.viewReport(jasperPrint, false);  
        } catch (JRException ex) {  
            JOptionPane.showMessageDialog(null, ex);  
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
        
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
         new FuncionarioBancoHorasVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        new FuncionarioVIEW().setVisible(true);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new ProdutoPesquisarVIEW().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        HashMap parametros = new HashMap();  
        RelatorioDAO dao = new RelatorioDAO();
        
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy", Locale.getDefault());
        String formatted = dateFormat.format(LocalDate.now().plusYears(1).toDate());
        System.out.println("formtado: "+formatted);
        String data_entrega = JOptionPane.showInputDialog(null, "Insira uma data de entrega: ", formatted);
        
       

        String tipo_pedido = "DIVERSOS";
        parametros.put("tipo_pedido", tipo_pedido);
        parametros.put("data_entrega", data_entrega);
        parametros.put("data_entrega_str", data_entrega);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        
        
        JRResultSetDataSource jrRS = new JRResultSetDataSource(dao.relatorio_vendas_DATA(tipo_pedido, data_entrega));  
        JasperPrint jasperPrint;  
       
        try {  
            //PEGANDO DO DIRETORIO MAZIN
            //jasperPrint = JasperFillManager.fillReport("\\\\"+TDG_SIS_VIEW.ip_servidor+"\\TDG_sis_prod\\relatorios\\"+TDG_SIS_VIEW.banco_selecionado+"\\n_pedido.jasper" , parametros, jrRS);  
            
            
            InputStream inputStream = getClass().getResourceAsStream( "/relatorios_ireport/relatorio_vendas_montado_data.jasper" );
            jasperPrint = JasperFillManager.fillReport(inputStream, parametros, jrRS);  
            JasperViewer.viewReport(jasperPrint, false);  
        } catch (JRException ex) {  
            JOptionPane.showMessageDialog(null, ex);  
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ProdutoFichaVIEW().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalVIEW().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cliente;
    private javax.swing.JButton btn_Consumo_Malha;
    private javax.swing.JButton btn_Corte;
    private javax.swing.JButton btn_Corte1;
    private javax.swing.JButton btn_Entrada_Estoque;
    private javax.swing.JButton btn_Espedicao;
    private javax.swing.JButton btn_Etq_Codigo_Barras;
    private javax.swing.JButton btn_Itens_Pedido;
    private javax.swing.JButton btn_Ordem_Corte;
    private javax.swing.JButton btn_Pedidos;
    private javax.swing.JButton btn_Producao_Bordado;
    private javax.swing.JButton btn_Produto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_Item_Pedido;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
