/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CTR.tdgCTR;
import DTO.ProdutoDTO;


import dao.ProdutoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;

/**
 *
 * @author PeDr0_HuG0
 */
public class ProdutoCategoriaVIEW extends javax.swing.JFrame {

    /**
     * Creates new form CoresVIEW
     */
    public ProdutoCategoriaVIEW() {
        initComponents();
        tdgCTR.considerarEnterComoTab(txt_rendimento);
        tdgCTR.considerarEnterComoTab(jComboBox_categoria);
        tdgCTR.considerarEnterComoTab(jComboBox_tipo_tamanho);
        tdgCTR.reagirEnter(btn_adicionar);
        tdgCTR.auto_selecionar(txt_rendimento);
        setar_rendimento();
    }
    private String grade;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        btn_Excluir = new javax.swing.JButton();
        btn_Listar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_rendimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_categoria = new javax.swing.JComboBox();
        btn_adicionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_tipo_tamanho = new javax.swing.JComboBox();
        jRadioButton1111 = new javax.swing.JRadioButton();
        jRadioButton1221 = new javax.swing.JRadioButton();
        jRadioButton1122 = new javax.swing.JRadioButton();
        jRadioButton2211 = new javax.swing.JRadioButton();
        jRadioButton2112 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton111 = new javax.swing.JRadioButton();
        jRadioButton122 = new javax.swing.JRadioButton();
        jRadioButton112 = new javax.swing.JRadioButton();
        jRadioButton221 = new javax.swing.JRadioButton();
        jRadioButton211 = new javax.swing.JRadioButton();
        jRadioButton121 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIAR CATEGORIA");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cores Cadastradas"));

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Listar.setText("LISTAR");
        btn_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CATEGORIA", "RENDIMENTO", "TIPO_TAMANHO", "GRADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
        }
        /*ocultar coluna ID da tabela
        jTable1.getColumnModel().getColumn( 0 ).setMaxWidth( 0 );
        jTable1.getColumnModel().getColumn( 0 ).setMinWidth( 0 );
        jTable1.getTableHeader().getColumnModel().getColumn( 0 ).setMaxWidth( 0 );
        jTable1.getTableHeader().getColumnModel().getColumn( 0 ).setMinWidth( 0 );
        //fim ocultar
        */

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Excluir))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Listar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria Produto"));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rendimento:");

        txt_rendimento.setText("1.0");
        txt_rendimento.setToolTipText("");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Categoria:");

        jComboBox_categoria.setEditable(true);
        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01 MACHAO", "02 GOLA CARECA", "03 GOLA V", "04 GOLA POLO", "05 CARECA ESPECIAL", "06 V ESPECIAL", "07 POLO ESPECIAL", "08 CARECA BABY", "09 CARECA KIDS", "10 CARECA JUVENIL", "11 CARECA SWAG", "12 V BABY", "13 V KIDS", "14 V JUVENIL", "15 POLO BABY", "16 POLO KIDS", "17 POLO JUVENIL", "18 CARECA ML", "19 V ML", "20 POLO ML", "21 PIQUET", "22 P001", " " }));
        jComboBox_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriaActionPerformed(evt);
            }
        });

        btn_adicionar.setText("Adicionar");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo Tamanho:");

        jComboBox_tipo_tamanho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "JUVENIL", "ESPECIAL", "BABY", "KIDS" }));
        jComboBox_tipo_tamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipo_tamanhoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1111);
        jRadioButton1111.setText("1 1 1 1");
        jRadioButton1111.setFocusable(false);
        jRadioButton1111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1111ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1221);
        jRadioButton1221.setText("1 2 2 1");
        jRadioButton1221.setFocusable(false);
        jRadioButton1221.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1221ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1122);
        jRadioButton1122.setText("1 1 2 2");
        jRadioButton1122.setFocusable(false);
        jRadioButton1122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1122ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2211);
        jRadioButton2211.setText("2 2 1 1");
        jRadioButton2211.setFocusable(false);
        jRadioButton2211.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2211ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2112);
        jRadioButton2112.setText("2 1 1 2");
        jRadioButton2112.setFocusable(false);
        jRadioButton2112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2112ActionPerformed(evt);
            }
        });

        jLabel3.setText("Grade Padrao:");

        buttonGroup1.add(jRadioButton111);
        jRadioButton111.setText("1 1 1");
        jRadioButton111.setFocusable(false);
        jRadioButton111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton111ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton122);
        jRadioButton122.setText("1 2 2");
        jRadioButton122.setFocusable(false);
        jRadioButton122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton122ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton112);
        jRadioButton112.setText("1 1 2");
        jRadioButton112.setFocusable(false);
        jRadioButton112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton112ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton221);
        jRadioButton221.setText("2 2 1 ");
        jRadioButton221.setFocusable(false);
        jRadioButton221.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton221ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton211);
        jRadioButton211.setText("2 1 1 ");
        jRadioButton211.setFocusable(false);
        jRadioButton211.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton211ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton121);
        jRadioButton121.setText("1 2 1 ");
        jRadioButton121.setFocusable(false);
        jRadioButton121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton121ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton111)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton122)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton221)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton211)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton121)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1111)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1221)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1122)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2211)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2112)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBox_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_rendimento)
                            .addComponent(jComboBox_tipo_tamanho, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_rendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_tipo_tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1111)
                    .addComponent(jRadioButton1221)
                    .addComponent(jRadioButton1122)
                    .addComponent(jRadioButton2211)
                    .addComponent(jRadioButton2112)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton111)
                    .addComponent(jRadioButton122)
                    .addComponent(jRadioButton112)
                    .addComponent(jRadioButton221)
                    .addComponent(jRadioButton211)
                    .addComponent(jRadioButton121))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_adicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRadioButton111.setVisible(false);
        jRadioButton122.setVisible(false);
        jRadioButton112.setVisible(false);
        jRadioButton221.setVisible(false);
        jRadioButton211.setVisible(false);
        jRadioButton121.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void setar_rendimento(){
        switch (jComboBox_categoria.getSelectedItem().toString()) {
            case "01 MACHAO":
            txt_rendimento.setText("7");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");            
            break;
            //4,8    
            case "02 GOLA CARECA":
            txt_rendimento.setText("4.8");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;
            case "03 GOLA V":
            txt_rendimento.setText("4.8");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;
            case "04 GOLA POLO":
            txt_rendimento.setText("4.8");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;
            //ESPECIAL 2,5
            case "05 CARECA ESPECIAL":
            txt_rendimento.setText("2.5");
            jComboBox_tipo_tamanho.setSelectedItem("ESPECIAL");
            break;
            case "06 V ESPECIAL":
            txt_rendimento.setText("2.5");
            jComboBox_tipo_tamanho.setSelectedItem("ESPECIAL");
            break;    
            case "07 POLO ESPECIAL":
            txt_rendimento.setText("2.5");
            jComboBox_tipo_tamanho.setSelectedItem("ESPECIAL");
            break;
      
            //BABY  X
            case "08 CARECA BABY":
            txt_rendimento.setText("1");
            jComboBox_tipo_tamanho.setSelectedItem("BABY");
            break;
            
            //KIDS  X
            case "09 CARECA KIDS":
            txt_rendimento.setText("1");
            jComboBox_tipo_tamanho.setSelectedItem("KIDS");
            break;
            
            //JUVENIL 6
            case "10 CARECA JUVENIL":
            txt_rendimento.setText("6");
            jComboBox_tipo_tamanho.setSelectedItem("JUVENIL");
            break;
            
            //CARECA SWAG 11
            case "11 CARECA SWAG":
            txt_rendimento.setText("4.4");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;


            case "12 V BABY":
            txt_rendimento.setText("1");
            jComboBox_tipo_tamanho.setSelectedItem("BABY");
            break;
            
            
            case "13 V KIDS":
            txt_rendimento.setText("1");
            jComboBox_tipo_tamanho.setSelectedItem("KIDS");
            break;
                
            case "14 V JUVENIL":
            txt_rendimento.setText("6");
            jComboBox_tipo_tamanho.setSelectedItem("JUVENIL");
            break;
   
            case "15 POLO BABY":
            txt_rendimento.setText("1");
            jComboBox_tipo_tamanho.setSelectedItem("BABY");
            break;
            
            
            case "16 POLO KIDS":
            txt_rendimento.setText("1");
            jComboBox_tipo_tamanho.setSelectedItem("KIDS");
            break;
         
            case "17 POLO JUVENIL":
            txt_rendimento.setText("6");
            jComboBox_tipo_tamanho.setSelectedItem("JUVENIL");
            break;
            //MANGA LONGA 2,5    
            case "18 CARECA ML":
            txt_rendimento.setText("2.5");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;
            case "19 V ML":
            txt_rendimento.setText("2.5");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;
            case "20 POLO ML":
            txt_rendimento.setText("2.5");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;
            //PIQUET 3,8    
            case "21 PIQUET":
            txt_rendimento.setText("3.8");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;
            //PIQUET 3,8    
            case "22 P001":
            txt_rendimento.setText("3.8");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            break;      
            default:
            txt_rendimento.setText("1");
            jComboBox_tipo_tamanho.setSelectedItem("NORMAL");
            }
    }
    
    
    private void btn_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarActionPerformed
        // TODO add your handling code here:
        ProdutoDAO dao = new ProdutoDAO();
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel(); 
            
        model.setNumRows(0);
        for (ProdutoDTO produtos : dao.listarCategorias()) {
            model.addRow(new Object[]{produtos.getId(),produtos.getCategoria(), produtos.getRendimento(), produtos.getTipo_tamanho(), produtos.getGrade()});
        }
    }//GEN-LAST:event_btn_ListarActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed

       
        ProdutoDTO produtos = new ProdutoDTO();

        Integer linhaSelecionada = -1;
        linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada >= 0) {//se linha selecionada

            Integer id = (Integer) jTable1.getValueAt(linhaSelecionada, 0);
            String categoria = (String) jTable1.getValueAt(linhaSelecionada, 1);

            //Confirmação
            String message = "Deseja realmente excluir a categoria: "+categoria+" ?";
            String title = "Confirmação";
            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION)
            {//sim
                //se confirmou
                DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
                produtos.setId(id);//setar o id pra excluir
                produtos.setCategoria(categoria);
                ProdutoDAO dao = new ProdutoDAO();
                if (dao.excluir_categoria(produtos)){
                    JOptionPane.showMessageDialog(null, "Categoria: "+categoria+" excluido com sucesso!");
                    model.removeRow(linhaSelecionada);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Erro, a categoria "+categoria+" não foi excluida!");
                }
                
            }else{
                //não confirmou
            }

        }
        else{ //se linha não estiver selecionada
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }   // fim linha selecionada
      
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        // TODO add your handling code here:
        if ( (txt_rendimento.getText() == null || txt_rendimento.getText().equals("")) || (jComboBox_categoria.getSelectedItem() == null || jComboBox_categoria.getSelectedItem().equals("")) || grade == null ){
            JOptionPane.showMessageDialog(null, "COMPLETE TODOS OS DADOS!");
        }else{
            adicionar_categoria();
            jComboBox_categoria.requestFocus();
        }
        
        
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void jRadioButton1221ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1221ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "1221";
    }//GEN-LAST:event_jRadioButton1221ActionPerformed

    private void jRadioButton1122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1122ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "1122";
    }//GEN-LAST:event_jRadioButton1122ActionPerformed

    private void jRadioButton2211ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2211ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "2211";
    }//GEN-LAST:event_jRadioButton2211ActionPerformed

    private void jRadioButton2112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2112ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "2112";
    }//GEN-LAST:event_jRadioButton2112ActionPerformed

    private void jRadioButton111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton111ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "111";
    }//GEN-LAST:event_jRadioButton111ActionPerformed

    private void jRadioButton122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton122ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "122";
    }//GEN-LAST:event_jRadioButton122ActionPerformed

    private void jRadioButton112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton112ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "112";
    }//GEN-LAST:event_jRadioButton112ActionPerformed

    private void jRadioButton221ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton221ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "221";
    }//GEN-LAST:event_jRadioButton221ActionPerformed

    private void jRadioButton211ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton211ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "211";
    }//GEN-LAST:event_jRadioButton211ActionPerformed

    private void jRadioButton121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton121ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "121";
    }//GEN-LAST:event_jRadioButton121ActionPerformed

    private void jRadioButton1111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1111ActionPerformed
        // TODO add your handling code here:
        btn_adicionar.requestFocus();
        grade = "1111";
    }//GEN-LAST:event_jRadioButton1111ActionPerformed

    private void jComboBox_tipo_tamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipo_tamanhoActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        if ( (jComboBox_tipo_tamanho.getSelectedItem()=="ESPECIAL")
                || (jComboBox_tipo_tamanho.getSelectedItem()=="BABY") 
                || (jComboBox_tipo_tamanho.getSelectedItem()=="KIDS")
           ){
            jRadioButton111.setVisible(true);
            jRadioButton112.setVisible(true);
            jRadioButton121.setVisible(true);
            jRadioButton122.setVisible(true);
            jRadioButton211.setVisible(true);
            jRadioButton221.setVisible(true);
            
            //false
            jRadioButton1111.setVisible(false);
            jRadioButton1122.setVisible(false);
            jRadioButton1221.setVisible(false);
            jRadioButton2112.setVisible(false);
            jRadioButton2211.setVisible(false);
        }else{
            jRadioButton111.setVisible(false);
            jRadioButton112.setVisible(false);
            jRadioButton121.setVisible(false);
            jRadioButton122.setVisible(false);
            jRadioButton211.setVisible(false);
            jRadioButton221.setVisible(false);
            
            //false
            jRadioButton1111.setVisible(true);
            jRadioButton1122.setVisible(true);
            jRadioButton1221.setVisible(true);
            jRadioButton2112.setVisible(true);
            jRadioButton2211.setVisible(true);
        }
        
    }//GEN-LAST:event_jComboBox_tipo_tamanhoActionPerformed

    private void jComboBox_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaActionPerformed
        // TODO add your handling code here:
        setar_rendimento();
    }//GEN-LAST:event_jComboBox_categoriaActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        ProdutoDTO produtos = new ProdutoDTO();
        if ("tableCellEditor".equals(evt.getPropertyName()))
		{   
                    Integer linhaSelecionada = -1;
                    linhaSelecionada = jTable1.getSelectedRow();
                    
                    if (linhaSelecionada >= 0) {
                                                
                        /*
                        String categoria_antiga;
                        
                        categoria_antiga = (String) jTable1.getValueAt(linhaSelecionada, 1);
                        */
                        if (jTable1.isEditing()){//começou a editar, pegar o nome que estava a categoria
                        /*    
                        System.out.println("Está Editing?!");
                        categoria_antiga = (String) jTable1.getValueAt(linhaSelecionada, 1);
                        System.out.println("Copiou: "+categoria_antiga);
                        produtos.setCategoria_antiga(categoria_antiga);
                        */
                        }else{//terminou de editar, atualizar campos
                                Integer id = (Integer) jTable1.getValueAt(linhaSelecionada, 0);
                                String categoria = (String) jTable1.getValueAt(linhaSelecionada, 1);
                                Double rendimento = (Double) jTable1.getValueAt(linhaSelecionada, 2);
                                String tipo_tamanho = (String) jTable1.getValueAt(linhaSelecionada, 3);
                                String grade = (String) jTable1.getValueAt(linhaSelecionada, 4);
                                
                                
                                produtos.setId(id);//setar o id pra excluir
                                produtos.setCategoria(categoria);
                                //produtos.setCategoria_antiga(categoria_antiga);
                                produtos.setRendimento(rendimento);
                                produtos.setTipo_tamanho(tipo_tamanho);
                                produtos.setGrade(grade);
                                
                                ProdutoDAO dao = new ProdutoDAO();
                                if (dao.atualizar_categoria(produtos) /*(dao.atualizar_descricao_produtos(produtos)) */ ){
                                    System.out.println("categoria atualizada");
                                    //listar?
                                }
                                else {
                                    System.out.println(" Não atualizou categoria");
                                }
                                
                            
                        }
                        
                        
                    
                    
		          
                                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Selecione uma linha!");
                    }
                            
		}
    }//GEN-LAST:event_jTable1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Edite direto da tabela.");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void adicionar_categoria(){
        ProdutoDTO produtos = new ProdutoDTO();
        
        produtos.setCategoria(jComboBox_categoria.getSelectedItem().toString());
        produtos.setRendimento( Double.parseDouble(txt_rendimento.getText()) );
        produtos.setTipo_tamanho(jComboBox_tipo_tamanho.getSelectedItem().toString());
        
        produtos.setGrade(grade);
        
        
        
        ProdutoDAO dao = new ProdutoDAO();
        if (dao.adiciona_categoria(produtos)){
            DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{produtos.getId(),produtos.getCategoria(), produtos.getRendimento(), produtos.getTipo_tamanho(), produtos.getGrade()});
            jComboBox_categoria.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "ERRO AO CATEGORIA");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoCategoriaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoCategoriaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoCategoriaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoCategoriaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoCategoriaVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Listar;
    private javax.swing.JButton btn_adicionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox_categoria;
    private javax.swing.JComboBox jComboBox_tipo_tamanho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton111;
    private javax.swing.JRadioButton jRadioButton1111;
    private javax.swing.JRadioButton jRadioButton112;
    private javax.swing.JRadioButton jRadioButton1122;
    private javax.swing.JRadioButton jRadioButton121;
    private javax.swing.JRadioButton jRadioButton122;
    private javax.swing.JRadioButton jRadioButton1221;
    private javax.swing.JRadioButton jRadioButton211;
    private javax.swing.JRadioButton jRadioButton2112;
    private javax.swing.JRadioButton jRadioButton221;
    private javax.swing.JRadioButton jRadioButton2211;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_rendimento;
    // End of variables declaration//GEN-END:variables
}
