/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CTR.tdgCTR;
import DTO.ColecaoDTO;
import dao.ColecaoDAO;
import java.awt.Toolkit;


import javax.swing.JOptionPane;
import javax.swing.JPasswordField;


/**
 *
 * @author PeDr0_HuG0
 */
public class TDG_SIS_VIEW extends javax.swing.JFrame {
public static String banco_selecionado, ip_servidor, usuario_banco, senha_banco, banco_principal;

    /**
     * Creates new form InicialVIEW
     */
    public TDG_SIS_VIEW() {
        initComponents();
        
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/tdgsimbolo.png")));
        //não abre fora do netbeans.
        
        
        setLocationRelativeTo( null );
        //ip_servidor = "192.168.1.155";
        ip_servidor = "localhost";
        usuario_banco = "postgres";
        senha_banco = "dba";
        banco_principal = "TDG_SIS";
        //banco_principal = "TDG_SIS_TESTE";
        buscar_colecao();
        btn_Entrar.requestFocus();
        
        
        //setar ip correto no FACTORY(conexao)
        tdgCTR.reagirEnter(btn_Entrar);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Colecao = new javax.swing.JComboBox();
        btn_Entrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TDG SIS");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione uma Coleção"));
        jPanel2.setToolTipText("");

        jLabel1.setText("Coleção:");

        jComboBox_Colecao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_Entrar.setText("Entrar");
        btn_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarActionPerformed(evt);
            }
        });

        jButton2.setText("Gerenciar Coleções");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Colecao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Colecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Entrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarActionPerformed
        // TODO add your handling code here:
        //setando variavel global o banco selecionado
        banco_selecionado = jComboBox_Colecao.getSelectedItem().toString();
        new PrincipalVIEW().setVisible(true);
        TDG_SIS_VIEW.this.dispose();
        
    }//GEN-LAST:event_btn_EntrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Confirmação
                                String message = "Informe a senha:";
                                String title = "Informe a senha";
                                
                                /*
                                String resposta = JOptionPane.showInputDialog(null, message, title, JOptionPane.PLAIN_MESSAGE);
                                
                                if (resposta == null || resposta.equals("") || ((!resposta.equals("123")))) 
                                {
                                    JOptionPane.showMessageDialog(null, "Senha invalida.");
                                }else{
                                    new ColecaoVIEW().setVisible(true);
                                    TDG_SIS_VIEW.this.dispose();
                                }
                                */
                                JPasswordField pwd = new JPasswordField(10);
                                
                                
                                
                                int resposta = JOptionPane.showConfirmDialog(null, pwd,title,JOptionPane.OK_CANCEL_OPTION);
                                
                                System.out.println("resp: "+resposta+" pwd: "+pwd.getText() );
                                if(resposta < 0)
                                {
                                 //cancelou   
                                }else{//informou algo ou deu ok
                                   if (pwd.getText().equals("") || ((!pwd.getText().equals("123")))) {
                                        JOptionPane.showMessageDialog(null, "Senha invalida.");
                                   }else{
                                        new ColecaoVIEW().setVisible(true);
                                        TDG_SIS_VIEW.this.dispose();
                                   }
                                }
                                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscar_colecao(){
        
        ColecaoDAO dao = new ColecaoDAO();
        jComboBox_Colecao.removeAllItems();
        //pegando dados colecao
        
        for (ColecaoDTO c : dao.getColecao()) {
            jComboBox_Colecao.addItem(c.getColecao());
        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TDG_SIS_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TDG_SIS_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TDG_SIS_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TDG_SIS_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TDG_SIS_VIEW().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox_Colecao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
